version: '3'

services:
  fhir-ui:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: development
    #        mem_limit: 1g  # Set a memory limit of 1GB
    environment:
      SERVER_PORT: 3000
      CLIENT_ID: client
      CLIENT_SECRET: secret
      AUTH_JWKS_URL: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_yV7wvD4xD/.well-known/jwks.json
      AUTH_ISSUER: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_yV7wvD4xD
      AUTH_CODE_FLOW_URL: https://bwell-dev.auth.us-east-1.amazoncognito.com
      AUTH_CODE_FLOW_CLIENT_ID: 5et51l3beeahp016i4qe6hurtr
      AUTH_ENABLED: 1
      REDIRECT_TO_LOGIN: 1
      AUTH_CUSTOM_GROUP: 'cognito:groups'
      AUTH_CUSTOM_SCOPE: 'custom:scope'
      LOG_DEBUG: 1
      ENV: local
      ENVIRONMENT: local
      FHIR_SERVER_URL: http://localhost:3000
    ports:
      - '5051:3000'
    volumes:
      - ./src:/srv/src/src
      - ./dist:/srv/src/dist
      - ./build:/srv/src/build
      - ./package.json:/srv/src/package.json
      - ./yarn.lock:/srv/src/yarn.lock
      - ./tsconfig.json:/srv/src/tsconfig.json
      - ./babel.config.json:/srv/src/babel.config.json
    command: yarn run dev
    healthcheck:
      test: [ 'CMD-SHELL', 'curl --silent --fail localhost:3000/health || exit 1' ]

  fhir:
    depends_on:
      - mongo
    image: imranq2/node-fhir-server-mongo:3.2.72
    # To use local fhir code, comment above line and uncomment below
#    build:
#      dockerfile: Dockerfile
#      context: ../fhir-server
    environment:
      SERVER_PORT: 3000
      MONGO_DB_NAME: fhir
      MONGO_URL: mongodb://mongo:27017
      AUDIT_EVENT_MONGO_DB_NAME: fhir
      AUDIT_EVENT_MONGO_URL: mongodb://mongo:27017
      RESOURCE_SERVER: http://fhir:3000/
      AUTH_SERVER_URI: http://myauthzserver.com
      CLIENT_ID: client
      CLIENT_SECRET: secret
      INTROSPECTION_URL: https://myauthzserver.com/introspect
      CHECK_ACCESS_TAG_ON_SAVE: 1
      IS_PRODUCTION: ""
      RETURN_BUNDLE: "1"
      VALIDATE_SCHEMA: "1"
      AUTH_ENABLED: "0"
      ENABLE_GRAPHQL: "1"
      LOGLEVEL: "DEBUG"
      SET_INDEX_HINTS: 0
      CREATE_INDEX_ON_COLLECTION_CREATION: 1
      USE_TWO_STEP_SEARCH_OPTIMIZATION: "1"
      STREAM_RESPONSE: "1"
      LOG_STREAM_STEPS: "0"
      PARTITION_RESOURCES: 'AuditEvent'
      COLLECTIONS_ACCESS_INDEX: "all"
      USE_ACCESS_INDEX: 1
      ENABLE_PATIENT_FILTERING: "1"
      ACCESS_TAGS_INDEXED: "medstar,Thedacare,bwell"
      ENABLE_GLOBAL_ID: 1
    ports:
      - '3000:3000'
    command: yarn start
    healthcheck:
        test: ["CMD-SHELL", "curl --silent --fail localhost:3000/health || exit 1"]

  mongo:
#    image: docker.io/bitnami/mongodb:4.4.9
    image: mongo:5.0.21
    ports:
      - '27017:27017'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo mongo:27017/test --quiet

  warehouse:
    image: mariadb:10.4.31
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: fhir_rpt
    ports:
      - '33061:3306'
    command: --sql-mode="STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION"
    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]

volumes:
  mysql_data:
  mongo_data:
