version: '3'

services:
  fhir-ui:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: development
    #        mem_limit: 1g  # Set a memory limit of 1GB
    environment:
      SERVER_PORT: 3000
      CLIENT_ID: client
      CLIENT_SECRET: secret
      AUTH_JWKS_URL: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_yV7wvD4xD/.well-known/jwks.json
      AUTH_ISSUER: https://cognito-idp.us-east-1.amazonaws.com/us-east-1_yV7wvD4xD
      AUTH_CODE_FLOW_URL: https://bwell-dev.auth.us-east-1.amazoncognito.com
      AUTH_CODE_FLOW_CLIENT_ID: 5et51l3beeahp016i4qe6hurtr
      AUTH_ENABLED: 0
      REDIRECT_TO_LOGIN: 1
      AUTH_CUSTOM_GROUP: 'cognito:groups'
      AUTH_CUSTOM_SCOPE: 'custom:scope'
      LOG_DEBUG: 1
      ENV: local
      ENVIRONMENT: local
      FHIR_SERVER_URL: http://localhost:3000
    ports:
      - '5051:3000'
    volumes:
      - ./src:/srv/src/src
      - ./dist:/srv/src/dist
      - ./build:/srv/src/build
      - ./package.json:/srv/src/package.json
      - ./yarn.lock:/srv/src/yarn.lock
      - ./tsconfig.json:/srv/src/tsconfig.json
      - ./babel.config.json:/srv/src/babel.config.json
    command: yarn run dev
    healthcheck:
      test: [ 'CMD-SHELL', 'curl --silent --fail localhost:3000/health || exit 1' ]
