// This file is auto-generated by generate_components so do not edit manually

/**
Account
    A financial tool for tracking value accrued for a particular purpose.  In the
    healthcare field, used to track charges for a patient, cost centers, etc.
    If the element is present, it must have either a @value, an @id, or extensions
*/

import React from 'react';
import { Link } from 'react-router';
import { TAccount } from '../../types/resources/Account';

// Import all the partial resource
import Partials from '../../partials';
import { IdentifierSystem } from '../../utils/identifierSystem';

const Account = ({ resource }: { resource: TAccount }): React.ReactElement => {
    const tagUUID = resource?.meta?.tag?.find((s) => s.system === IdentifierSystem.uuid)?.code;
    const uuid = tagUUID ? tagUUID : resource.id;

    return (
        <>
            <Link title="Direct link to Resource" to={`/4_0_0/${resource.resourceType}/${uuid}`}>
                {resource.resourceType}/{uuid}
            </Link>
            {
                resource.id !== undefined && resource.id !== null &&
                <Partials.String
                    string={resource.id}
                    name='Id'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='id'
                />
            }
            {
                resource.meta !== undefined && resource.meta !== null &&
                <Partials.Meta
                    meta={resource.meta}
                    name='Meta'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='meta'
                />
            }
            {
                resource.implicitRules !== undefined && resource.implicitRules !== null &&
                <Partials.Uri
                    uri={resource.implicitRules}
                    name='Implicit Rules'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='implicit-rules'
                />
            }
            {
                resource.language &&
                <Partials.Code code={resource.language} name='Language'/>
            }
            {
                resource.text !== undefined && resource.text !== null &&
                <Partials.Narrative
                    narrative={resource.text}
                    name='Text'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='text'
                />
            }
            {
                resource.extension !== undefined && resource.extension !== null &&
                <Partials.Extension
                    extension={resource.extension}
                    name='Extension'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='extension'
                />
            }
            {
                resource.modifierExtension !== undefined && resource.modifierExtension !== null &&
                <Partials.Extension
                    extension={resource.modifierExtension}
                    name='Modifier Extension'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='modifier-extension'
                />
            }
            {
                resource.identifier !== undefined && resource.identifier !== null &&
                <Partials.Identifier
                    identifier={resource.identifier}
                    name='Identifier'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='identifier'
                />
            }
            {
                resource.status &&
                <Partials.Code code={resource.status} name='Status'/>
            }
            {
                resource.type !== undefined && resource.type !== null &&
                <Partials.CodeableConcept
                    codeableConcept={resource.type}
                    name='Type'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='type'
                />
            }
            {
                resource.name !== undefined && resource.name !== null &&
                <Partials.String
                    string={resource.name}
                    name='Name'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='name'
                />
            }
            {
                resource.subject !== undefined && resource.subject !== null &&
                <Partials.Reference
                    reference={resource.subject}
                    name='Subject'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='subject'
                />
            }
            {
                resource.servicePeriod !== undefined && resource.servicePeriod !== null &&
                <Partials.Period
                    period={resource.servicePeriod}
                    name='Service Period'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='service-period'
                />
            }
            {
                resource.coverage !== undefined && resource.coverage !== null &&
                <Partials.Reference
                    reference={resource.coverage}
                    name='Coverage'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='coverage'
                    field='coverage'
                />
            }
            {
                resource.owner !== undefined && resource.owner !== null &&
                <Partials.Reference
                    reference={resource.owner}
                    name='Owner'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='owner'
                />
            }
            {
                resource.description !== undefined && resource.description !== null &&
                <Partials.String
                    string={resource.description}
                    name='Description'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='description'
                />
            }
            {
                resource.guarantor !== undefined && resource.guarantor !== null &&
                <Partials.Reference
                    reference={resource.guarantor}
                    name='Guarantor'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='guarantor'
                    field='party'
                />
            }
            {
                resource.partOf !== undefined && resource.partOf !== null &&
                <Partials.Reference
                    reference={resource.partOf}
                    name='Part Of'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='part-of'
                />
            }
        </>
    );
};

export default Account;
