// This file is auto-generated by generate_components so do not edit manually

/**
ActivityDefinition
    This resource allows for the definition of some activity to be performed,
    independent of a particular patient, practitioner, or other performance
    context.
    If the element is present, it must have either a @value, an @id, or extensions
*/

import React from 'react';
import { Link } from 'react-router';
import { TActivityDefinition } from '../../types/resources/ActivityDefinition';

// Import all the partial resource
import Partials from '../../partials';
import { IdentifierSystem } from '../../utils/identifierSystem';

const ActivityDefinition = ({ resource }: { resource: TActivityDefinition }): React.ReactElement => {
    const tagUUID = resource?.meta?.tag?.find((s) => s.system === IdentifierSystem.uuid)?.code;
    const uuid = tagUUID ? tagUUID : resource.id;

    return (
        <>
            <Link title="Direct link to Resource" to={`/4_0_0/${resource.resourceType}/${uuid}`}>
                {resource.resourceType}/{uuid}
            </Link>
            {
                resource.id !== undefined && resource.id !== null &&
                <Partials.String
                    string={resource.id}
                    name='Id'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='id'
                />
            }
            {
                resource.meta !== undefined && resource.meta !== null &&
                <Partials.Meta
                    meta={resource.meta}
                    name='Meta'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='meta'
                />
            }
            {
                resource.implicitRules !== undefined && resource.implicitRules !== null &&
                <Partials.Uri
                    uri={resource.implicitRules}
                    name='Implicit Rules'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='implicit-rules'
                />
            }
            {
                resource.language &&
                <Partials.Code code={resource.language} name='Language'/>
            }
            {
                resource.text !== undefined && resource.text !== null &&
                <Partials.Narrative
                    narrative={resource.text}
                    name='Text'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='text'
                />
            }
            {
                resource.extension !== undefined && resource.extension !== null &&
                <Partials.Extension
                    extension={resource.extension}
                    name='Extension'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='extension'
                />
            }
            {
                resource.modifierExtension !== undefined && resource.modifierExtension !== null &&
                <Partials.Extension
                    extension={resource.modifierExtension}
                    name='Modifier Extension'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='modifier-extension'
                />
            }
            {
                resource.url !== undefined && resource.url !== null &&
                <Partials.Uri
                    uri={resource.url}
                    name='Url'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='url'
                />
            }
            {
                resource.identifier !== undefined && resource.identifier !== null &&
                <Partials.Identifier
                    identifier={resource.identifier}
                    name='Identifier'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='identifier'
                />
            }
            {
                resource.version !== undefined && resource.version !== null &&
                <Partials.String
                    string={resource.version}
                    name='Version'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='version'
                />
            }
            {
                resource.name !== undefined && resource.name !== null &&
                <Partials.String
                    string={resource.name}
                    name='Name'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='name'
                />
            }
            {
                resource.title !== undefined && resource.title !== null &&
                <Partials.String
                    string={resource.title}
                    name='Title'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='title'
                />
            }
            {
                resource.subtitle !== undefined && resource.subtitle !== null &&
                <Partials.String
                    string={resource.subtitle}
                    name='Subtitle'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='subtitle'
                />
            }
            {
                resource.status &&
                <Partials.Code code={resource.status} name='Status'/>
            }
            {
                resource.experimental !== undefined && resource.experimental !== null &&
                <Partials.Boolean
                    boolean={resource.experimental}
                    name='Experimental'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='experimental'
                />
            }
            {
                resource.subjectCodeableConcept !== undefined && resource.subjectCodeableConcept !== null &&
                <Partials.CodeableConcept
                    codeableConcept={resource.subjectCodeableConcept}
                    name='Subject Codeable Concept'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='subject-codeable-concept'
                />
            }
            {
                resource.subjectReference !== undefined && resource.subjectReference !== null &&
                <Partials.Reference
                    reference={resource.subjectReference}
                    name='Subject Reference'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='subject-reference'
                />
            }
            {
                resource.subjectCanonical !== undefined && resource.subjectCanonical !== null &&
                <Partials.Canonical
                    canonical={resource.subjectCanonical}
                    name='Subject Canonical'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='subject-canonical'
                />
            }
            {
                resource.date !== undefined && resource.date !== null &&
                <Partials.DateTime
                    dateTime={resource.date}
                    name='Date'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='date'
                />
            }
            {
                resource.publisher !== undefined && resource.publisher !== null &&
                <Partials.String
                    string={resource.publisher}
                    name='Publisher'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='publisher'
                />
            }
            {
                resource.description !== undefined && resource.description !== null &&
                <Partials.Markdown
                    markdown={resource.description}
                    name='Description'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='description'
                />
            }
            {
                resource.jurisdiction !== undefined && resource.jurisdiction !== null &&
                <Partials.CodeableConcept
                    codeableConcept={resource.jurisdiction}
                    name='Jurisdiction'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='jurisdiction'
                />
            }
            {
                resource.purpose !== undefined && resource.purpose !== null &&
                <Partials.Markdown
                    markdown={resource.purpose}
                    name='Purpose'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='purpose'
                />
            }
            {
                resource.usage !== undefined && resource.usage !== null &&
                <Partials.String
                    string={resource.usage}
                    name='Usage'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='usage'
                />
            }
            {
                resource.copyright !== undefined && resource.copyright !== null &&
                <Partials.Markdown
                    markdown={resource.copyright}
                    name='Copyright'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='copyright'
                />
            }
            {
                resource.approvalDate !== undefined && resource.approvalDate !== null &&
                <Partials.Date
                    date={resource.approvalDate}
                    name='Approval Date'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='approval-date'
                />
            }
            {
                resource.lastReviewDate !== undefined && resource.lastReviewDate !== null &&
                <Partials.Date
                    date={resource.lastReviewDate}
                    name='Last Review Date'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='last-review-date'
                />
            }
            {
                resource.effectivePeriod !== undefined && resource.effectivePeriod !== null &&
                <Partials.Period
                    period={resource.effectivePeriod}
                    name='Effective Period'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='effective-period'
                />
            }
            {
                resource.topic !== undefined && resource.topic !== null &&
                <Partials.CodeableConcept
                    codeableConcept={resource.topic}
                    name='Topic'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='topic'
                />
            }
            {
                resource.relatedArtifact !== undefined && resource.relatedArtifact !== null &&
                <Partials.RelatedArtifact
                    relatedArtifact={resource.relatedArtifact}
                    name='Related Artifact'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='related-artifact'
                />
            }
            {
                resource.library !== undefined && resource.library !== null &&
                <Partials.Canonical
                    canonical={resource.library}
                    name='Library'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='library'
                />
            }
            {
                resource.kind &&
                <Partials.Code code={resource.kind} name='Kind'/>
            }
            {
                resource.profile !== undefined && resource.profile !== null &&
                <Partials.Canonical
                    canonical={resource.profile}
                    name='Profile'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='profile'
                />
            }
            {
                resource.code !== undefined && resource.code !== null &&
                <Partials.CodeableConcept
                    codeableConcept={resource.code}
                    name='Code'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='code'
                />
            }
            {
                resource.intent &&
                <Partials.Code code={resource.intent} name='Intent'/>
            }
            {
                resource.priority &&
                <Partials.Code code={resource.priority} name='Priority'/>
            }
            {
                resource.doNotPerform !== undefined && resource.doNotPerform !== null &&
                <Partials.Boolean
                    boolean={resource.doNotPerform}
                    name='Do Not Perform'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='do-not-perform'
                />
            }
            {
                resource.timingTiming !== undefined && resource.timingTiming !== null &&
                <Partials.Timing
                    timing={resource.timingTiming}
                    name='Timing Timing'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='timing-timing'
                />
            }
            {
                resource.timingDateTime !== undefined && resource.timingDateTime !== null &&
                <Partials.DateTime
                    dateTime={resource.timingDateTime}
                    name='Timing Date Time'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='timing-date-time'
                />
            }
            {
                resource.timingAge !== undefined && resource.timingAge !== null &&
                <Partials.Quantity
                    quantity={resource.timingAge}
                    name='Timing Age'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='timing-age'
                />
            }
            {
                resource.timingPeriod !== undefined && resource.timingPeriod !== null &&
                <Partials.Period
                    period={resource.timingPeriod}
                    name='Timing Period'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='timing-period'
                />
            }
            {
                resource.timingRange !== undefined && resource.timingRange !== null &&
                <Partials.Range
                    range={resource.timingRange}
                    name='Timing Range'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='timing-range'
                />
            }
            {
                resource.timingDuration !== undefined && resource.timingDuration !== null &&
                <Partials.Quantity
                    quantity={resource.timingDuration}
                    name='Timing Duration'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='timing-duration'
                />
            }
            {
                resource.location !== undefined && resource.location !== null &&
                <Partials.Reference
                    reference={resource.location}
                    name='Location'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='location'
                />
            }
            {
                resource.participant !== undefined && resource.participant !== null &&
                <Partials.ActivityDefinitionParticipant
                    participant={resource.participant}
                    name='Participant'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='participant'
                    field=''
                />
            }
            {
                resource.productReference !== undefined && resource.productReference !== null &&
                <Partials.Reference
                    reference={resource.productReference}
                    name='Product Reference'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='product-reference'
                />
            }
            {
                resource.productCodeableConcept !== undefined && resource.productCodeableConcept !== null &&
                <Partials.CodeableConcept
                    codeableConcept={resource.productCodeableConcept}
                    name='Product Codeable Concept'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='product-codeable-concept'
                />
            }
            {
                resource.quantity !== undefined && resource.quantity !== null &&
                <Partials.Quantity
                    quantity={resource.quantity}
                    name='Quantity'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='quantity'
                />
            }
            {
                resource.dosage !== undefined && resource.dosage !== null &&
                <Partials.Dosage
                    dosage={resource.dosage}
                    name='Dosage'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='dosage'
                />
            }
            {
                resource.bodySite !== undefined && resource.bodySite !== null &&
                <Partials.CodeableConcept
                    codeableConcept={resource.bodySite}
                    name='Body Site'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='body-site'
                />
            }
            {
                resource.specimenRequirement !== undefined && resource.specimenRequirement !== null &&
                <Partials.Reference
                    reference={resource.specimenRequirement}
                    name='Specimen Requirement'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='specimen-requirement'
                />
            }
            {
                resource.observationRequirement !== undefined && resource.observationRequirement !== null &&
                <Partials.Reference
                    reference={resource.observationRequirement}
                    name='Observation Requirement'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='observation-requirement'
                />
            }
            {
                resource.observationResultRequirement !== undefined && resource.observationResultRequirement !== null &&
                <Partials.Reference
                    reference={resource.observationResultRequirement}
                    name='Observation Result Requirement'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='observation-result-requirement'
                />
            }
            {
                resource.transform !== undefined && resource.transform !== null &&
                <Partials.Canonical
                    canonical={resource.transform}
                    name='Transform'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='transform'
                />
            }
            {
                resource.dynamicValue !== undefined && resource.dynamicValue !== null &&
                <Partials.ActivityDefinitionDynamicValue
                    dynamicValue={resource.dynamicValue}
                    name='Dynamic Value'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='dynamic-value'
                    field=''
                />
            }
        </>
    );
};

export default ActivityDefinition;
