// This file is auto-generated by generate_components so do not edit manually

/**
BiologicallyDerivedProduct
    A material substance originating from a biological entity intended to be
    transplanted or infused
    into another (possibly the same) biological entity.
    If the element is present, it must have either a @value, an @id, or extensions
*/

import React from 'react';
import { Link } from 'react-router';
import { TBiologicallyDerivedProduct } from '../../types/resources/BiologicallyDerivedProduct';

// Import all the partial resource
import Partials from '../../partials';
import { IdentifierSystem } from '../../utils/identifierSystem';

const BiologicallyDerivedProduct = ({ resource }: { resource: TBiologicallyDerivedProduct }): React.ReactElement => {
    const tagUUID = resource?.meta?.tag?.find((s) => s.system === IdentifierSystem.uuid)?.code;
    const uuid = tagUUID ? tagUUID : resource.id;

    return (
        <>
            <Link title="Direct link to Resource" to={`/4_0_0/${resource.resourceType}/${uuid}`}>
                {resource.resourceType}/{uuid}
            </Link>
            {
                resource.id !== undefined && resource.id !== null &&
                <Partials.String
                    string={resource.id}
                    name='Id'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='id'
                />
            }
            {
                resource.meta !== undefined && resource.meta !== null &&
                <Partials.Meta
                    meta={resource.meta}
                    name='Meta'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='meta'
                />
            }
            {
                resource.implicitRules !== undefined && resource.implicitRules !== null &&
                <Partials.Uri
                    uri={resource.implicitRules}
                    name='Implicit Rules'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='implicit-rules'
                />
            }
            {
                resource.language &&
                <Partials.Code code={resource.language} name='Language'/>
            }
            {
                resource.text !== undefined && resource.text !== null &&
                <Partials.Narrative
                    narrative={resource.text}
                    name='Text'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='text'
                />
            }
            {
                resource.extension !== undefined && resource.extension !== null &&
                <Partials.Extension
                    extension={resource.extension}
                    name='Extension'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='extension'
                />
            }
            {
                resource.modifierExtension !== undefined && resource.modifierExtension !== null &&
                <Partials.Extension
                    extension={resource.modifierExtension}
                    name='Modifier Extension'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='modifier-extension'
                />
            }
            {
                resource.identifier !== undefined && resource.identifier !== null &&
                <Partials.Identifier
                    identifier={resource.identifier}
                    name='Identifier'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='identifier'
                />
            }
            {
                resource.productCategory &&
                <Partials.Code code={resource.productCategory} name='Product Category'/>
            }
            {
                resource.productCode !== undefined && resource.productCode !== null &&
                <Partials.CodeableConcept
                    codeableConcept={resource.productCode}
                    name='Product Code'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='product-code'
                />
            }
            {
                resource.status &&
                <Partials.Code code={resource.status} name='Status'/>
            }
            {
                resource.request !== undefined && resource.request !== null &&
                <Partials.Reference
                    reference={resource.request}
                    name='Request'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='request'
                />
            }
            {
                resource.quantity !== undefined && resource.quantity !== null &&
                <Partials.Int
                    int={resource.quantity}
                    name='Quantity'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='quantity'
                />
            }
            {
                resource.parent !== undefined && resource.parent !== null &&
                <Partials.Reference
                    reference={resource.parent}
                    name='Parent'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='parent'
                />
            }
            {
                resource.collection !== undefined && resource.collection !== null &&
                <Partials.BiologicallyDerivedProductCollection
                    collection={resource.collection}
                    name='Collection'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='collection'
                    field=''
                />
            }
            {
                resource.processing !== undefined && resource.processing !== null &&
                <Partials.BiologicallyDerivedProductProcessing
                    processing={resource.processing}
                    name='Processing'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='processing'
                    field=''
                />
            }
            {
                resource.storage !== undefined && resource.storage !== null &&
                <Partials.BiologicallyDerivedProductStorage
                    storage={resource.storage}
                    name='Storage'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='storage'
                    field=''
                />
            }
        </>
    );
};

export default BiologicallyDerivedProduct;
