// This file is auto-generated by generate_components so do not edit manually

/**
Composition
    A set of healthcare-related information that is assembled together into a
    single logical package that provides a single coherent statement of meaning,
    establishes its own context and that has clinical attestation with regard to
    who is making the statement. A Composition defines the structure and narrative
    content necessary for a document. However, a Composition alone does not
    constitute a document. Rather, the Composition must be the first entry in a
    Bundle where Bundle.type=document, and any other resources referenced from
    Composition must be included as subsequent entries in the Bundle (for example
    Patient, Practitioner, Encounter, etc.).
    If the element is present, it must have either a @value, an @id, or extensions
*/

import React from 'react';
import { Link } from 'react-router';
import { TComposition } from '../../types/resources/Composition';

// Import all the partial resource
import Partials from '../../partials';
import { IdentifierSystem } from '../../utils/identifierSystem';

const Composition = ({ resource }: { resource: TComposition }): React.ReactElement => {
    const tagUUID = resource?.meta?.tag?.find((s) => s.system === IdentifierSystem.uuid)?.code;
    const uuid = tagUUID ? tagUUID : resource.id;

    return (
        <>
            <Link title="Direct link to Resource" to={`/4_0_0/${resource.resourceType}/${uuid}`}>
                {resource.resourceType}/{uuid}
            </Link>
            {
                resource.id !== undefined && resource.id !== null &&
                <Partials.String
                    string={resource.id}
                    name='Id'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='id'
                />
            }
            {
                resource.meta !== undefined && resource.meta !== null &&
                <Partials.Meta
                    meta={resource.meta}
                    name='Meta'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='meta'
                />
            }
            {
                resource.implicitRules !== undefined && resource.implicitRules !== null &&
                <Partials.Uri
                    uri={resource.implicitRules}
                    name='Implicit Rules'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='implicit-rules'
                />
            }
            {
                resource.language &&
                <Partials.Code code={resource.language} name='Language'/>
            }
            {
                resource.text !== undefined && resource.text !== null &&
                <Partials.Narrative
                    narrative={resource.text}
                    name='Text'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='text'
                />
            }
            {
                resource.extension !== undefined && resource.extension !== null &&
                <Partials.Extension
                    extension={resource.extension}
                    name='Extension'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='extension'
                />
            }
            {
                resource.modifierExtension !== undefined && resource.modifierExtension !== null &&
                <Partials.Extension
                    extension={resource.modifierExtension}
                    name='Modifier Extension'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='modifier-extension'
                />
            }
            {
                resource.identifier !== undefined && resource.identifier !== null &&
                <Partials.Identifier
                    identifier={resource.identifier}
                    name='Identifier'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='identifier'
                />
            }
            {
                resource.status &&
                <Partials.Code code={resource.status} name='Status'/>
            }
            {
                resource.type !== undefined && resource.type !== null &&
                <Partials.CodeableConcept
                    codeableConcept={resource.type}
                    name='Type'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='type'
                />
            }
            {
                resource.category !== undefined && resource.category !== null &&
                <Partials.CodeableConcept
                    codeableConcept={resource.category}
                    name='Category'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='category'
                />
            }
            {
                resource.subject !== undefined && resource.subject !== null &&
                <Partials.Reference
                    reference={resource.subject}
                    name='Subject'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='subject'
                />
            }
            {
                resource.encounter !== undefined && resource.encounter !== null &&
                <Partials.Reference
                    reference={resource.encounter}
                    name='Encounter'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='encounter'
                />
            }
            {
                resource.date !== undefined && resource.date !== null &&
                <Partials.DateTime
                    dateTime={resource.date}
                    name='Date'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='date'
                />
            }
            {
                resource.author !== undefined && resource.author !== null &&
                <Partials.Reference
                    reference={resource.author}
                    name='Author'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='author'
                />
            }
            {
                resource.title !== undefined && resource.title !== null &&
                <Partials.String
                    string={resource.title}
                    name='Title'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='title'
                />
            }
            {
                resource.confidentiality &&
                <Partials.Code code={resource.confidentiality} name='Confidentiality'/>
            }
            {
                resource.attester !== undefined && resource.attester !== null &&
                <Partials.CompositionAttester
                    attester={resource.attester}
                    name='Attester'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='attester'
                    field=''
                />
            }
            {
                resource.custodian !== undefined && resource.custodian !== null &&
                <Partials.Reference
                    reference={resource.custodian}
                    name='Custodian'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='custodian'
                />
            }
            {
                resource.event !== undefined && resource.event !== null &&
                <Partials.CompositionEvent
                    event={resource.event}
                    name='Event'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='event'
                    field=''
                />
            }
            {
                resource.section !== undefined && resource.section !== null &&
                <Partials.CompositionSection
                    section={resource.section}
                    name='Section'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='section'
                    field=''
                />
            }
        </>
    );
};

export default Composition;
