// This file is auto-generated by generate_components so do not edit manually

/**
Condition
    A clinical condition, problem, diagnosis, or other event, situation, issue, or
    clinical concept that has risen to a level of concern.
    If the element is present, it must have either a @value, an @id, or extensions
*/

import React from 'react';
import { Link } from 'react-router';
import { TCondition } from '../../types/resources/Condition';

// Import all the partial resource
import Partials from '../../partials';
import { IdentifierSystem } from '../../utils/identifierSystem';

const Condition = ({ resource }: { resource: TCondition }): React.ReactElement => {
    const tagUUID = resource?.meta?.tag?.find((s) => s.system === IdentifierSystem.uuid)?.code;
    const uuid = tagUUID ? tagUUID : resource.id;

    return (
        <>
            <Link title="Direct link to Resource" to={`/4_0_0/${resource.resourceType}/${uuid}`}>
                {resource.resourceType}/{uuid}
            </Link>
            {
                resource.id !== undefined && resource.id !== null &&
                <Partials.String
                    string={resource.id}
                    name='Id'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='id'
                />
            }
            {
                resource.meta !== undefined && resource.meta !== null &&
                <Partials.Meta
                    meta={resource.meta}
                    name='Meta'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='meta'
                />
            }
            {
                resource.implicitRules !== undefined && resource.implicitRules !== null &&
                <Partials.Uri
                    uri={resource.implicitRules}
                    name='Implicit Rules'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='implicit-rules'
                />
            }
            {
                resource.language &&
                <Partials.Code code={resource.language} name='Language'/>
            }
            {
                resource.text !== undefined && resource.text !== null &&
                <Partials.Narrative
                    narrative={resource.text}
                    name='Text'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='text'
                />
            }
            {
                resource.extension !== undefined && resource.extension !== null &&
                <Partials.Extension
                    extension={resource.extension}
                    name='Extension'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='extension'
                />
            }
            {
                resource.modifierExtension !== undefined && resource.modifierExtension !== null &&
                <Partials.Extension
                    extension={resource.modifierExtension}
                    name='Modifier Extension'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='modifier-extension'
                />
            }
            {
                resource.identifier !== undefined && resource.identifier !== null &&
                <Partials.Identifier
                    identifier={resource.identifier}
                    name='Identifier'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='identifier'
                />
            }
            {
                resource.clinicalStatus !== undefined && resource.clinicalStatus !== null &&
                <Partials.CodeableConcept
                    codeableConcept={resource.clinicalStatus}
                    name='Clinical Status'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='clinical-status'
                />
            }
            {
                resource.verificationStatus !== undefined && resource.verificationStatus !== null &&
                <Partials.CodeableConcept
                    codeableConcept={resource.verificationStatus}
                    name='Verification Status'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='verification-status'
                />
            }
            {
                resource.category !== undefined && resource.category !== null &&
                <Partials.CodeableConcept
                    codeableConcept={resource.category}
                    name='Category'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='category'
                />
            }
            {
                resource.severity !== undefined && resource.severity !== null &&
                <Partials.CodeableConcept
                    codeableConcept={resource.severity}
                    name='Severity'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='severity'
                />
            }
            {
                resource.code !== undefined && resource.code !== null &&
                <Partials.CodeableConcept
                    codeableConcept={resource.code}
                    name='Code'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='code'
                />
            }
            {
                resource.bodySite !== undefined && resource.bodySite !== null &&
                <Partials.CodeableConcept
                    codeableConcept={resource.bodySite}
                    name='Body Site'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='body-site'
                />
            }
            {
                resource.subject !== undefined && resource.subject !== null &&
                <Partials.Reference
                    reference={resource.subject}
                    name='Subject'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='subject'
                />
            }
            {
                resource.encounter !== undefined && resource.encounter !== null &&
                <Partials.Reference
                    reference={resource.encounter}
                    name='Encounter'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='encounter'
                />
            }
            {
                resource.onsetDateTime !== undefined && resource.onsetDateTime !== null &&
                <Partials.DateTime
                    dateTime={resource.onsetDateTime}
                    name='Onset Date Time'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='onset-date-time'
                />
            }
            {
                resource.onsetAge !== undefined && resource.onsetAge !== null &&
                <Partials.Quantity
                    quantity={resource.onsetAge}
                    name='Onset Age'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='onset-age'
                />
            }
            {
                resource.onsetPeriod !== undefined && resource.onsetPeriod !== null &&
                <Partials.Period
                    period={resource.onsetPeriod}
                    name='Onset Period'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='onset-period'
                />
            }
            {
                resource.onsetRange !== undefined && resource.onsetRange !== null &&
                <Partials.Range
                    range={resource.onsetRange}
                    name='Onset Range'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='onset-range'
                />
            }
            {
                resource.onsetString !== undefined && resource.onsetString !== null &&
                <Partials.String
                    string={resource.onsetString}
                    name='Onset String'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='onset-string'
                />
            }
            {
                resource.abatementDateTime !== undefined && resource.abatementDateTime !== null &&
                <Partials.DateTime
                    dateTime={resource.abatementDateTime}
                    name='Abatement Date Time'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='abatement-date-time'
                />
            }
            {
                resource.abatementAge !== undefined && resource.abatementAge !== null &&
                <Partials.Quantity
                    quantity={resource.abatementAge}
                    name='Abatement Age'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='abatement-age'
                />
            }
            {
                resource.abatementPeriod !== undefined && resource.abatementPeriod !== null &&
                <Partials.Period
                    period={resource.abatementPeriod}
                    name='Abatement Period'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='abatement-period'
                />
            }
            {
                resource.abatementRange !== undefined && resource.abatementRange !== null &&
                <Partials.Range
                    range={resource.abatementRange}
                    name='Abatement Range'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='abatement-range'
                />
            }
            {
                resource.abatementString !== undefined && resource.abatementString !== null &&
                <Partials.String
                    string={resource.abatementString}
                    name='Abatement String'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='abatement-string'
                />
            }
            {
                resource.recordedDate !== undefined && resource.recordedDate !== null &&
                <Partials.DateTime
                    dateTime={resource.recordedDate}
                    name='Recorded Date'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='recorded-date'
                />
            }
            {
                resource.recorder !== undefined && resource.recorder !== null &&
                <Partials.Reference
                    reference={resource.recorder}
                    name='Recorder'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='recorder'
                />
            }
            {
                resource.asserter !== undefined && resource.asserter !== null &&
                <Partials.Reference
                    reference={resource.asserter}
                    name='Asserter'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='asserter'
                />
            }
            {
                resource.stage !== undefined && resource.stage !== null &&
                <Partials.ConditionStage
                    stage={resource.stage}
                    name='Stage'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='stage'
                    field=''
                />
            }
            {
                resource.note !== undefined && resource.note !== null &&
                <Partials.Annotation
                    annotation={resource.note}
                    name='Note'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='note'
                />
            }
        </>
    );
};

export default Condition;
