// This file is auto-generated by generate_components so do not edit manually

/**
CoverageEligibilityRequest
    The CoverageEligibilityRequest provides patient and insurance coverage
    information to an insurer for them to respond, in the form of an
    CoverageEligibilityResponse, with information regarding whether the stated
    coverage is valid and in-force and optionally to provide the insurance details
    of the policy.
    If the element is present, it must have either a @value, an @id, or extensions
*/

import React from 'react';
import { Link } from 'react-router';
import { TCoverageEligibilityRequest } from '../../types/resources/CoverageEligibilityRequest';

// Import all the partial resource
import Partials from '../../partials';
import { IdentifierSystem } from '../../utils/identifierSystem';

const CoverageEligibilityRequest = ({ resource }: { resource: TCoverageEligibilityRequest }): React.ReactElement => {
    const tagUUID = resource?.meta?.tag?.find((s) => s.system === IdentifierSystem.uuid)?.code;
    const uuid = tagUUID ? tagUUID : resource.id;

    return (
        <>
            <Link title="Direct link to Resource" to={`/4_0_0/${resource.resourceType}/${uuid}`}>
                {resource.resourceType}/{uuid}
            </Link>
            {
                resource.id !== undefined && resource.id !== null &&
                <Partials.String
                    string={resource.id}
                    name='Id'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='id'
                />
            }
            {
                resource.meta !== undefined && resource.meta !== null &&
                <Partials.Meta
                    meta={resource.meta}
                    name='Meta'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='meta'
                />
            }
            {
                resource.implicitRules !== undefined && resource.implicitRules !== null &&
                <Partials.Uri
                    uri={resource.implicitRules}
                    name='Implicit Rules'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='implicit-rules'
                />
            }
            {
                resource.language &&
                <Partials.Code code={resource.language} name='Language'/>
            }
            {
                resource.text !== undefined && resource.text !== null &&
                <Partials.Narrative
                    narrative={resource.text}
                    name='Text'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='text'
                />
            }
            {
                resource.extension !== undefined && resource.extension !== null &&
                <Partials.Extension
                    extension={resource.extension}
                    name='Extension'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='extension'
                />
            }
            {
                resource.modifierExtension !== undefined && resource.modifierExtension !== null &&
                <Partials.Extension
                    extension={resource.modifierExtension}
                    name='Modifier Extension'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='modifier-extension'
                />
            }
            {
                resource.identifier !== undefined && resource.identifier !== null &&
                <Partials.Identifier
                    identifier={resource.identifier}
                    name='Identifier'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='identifier'
                />
            }
            {
                resource.status &&
                <Partials.Code code={resource.status} name='Status'/>
            }
            {
                resource.priority !== undefined && resource.priority !== null &&
                <Partials.CodeableConcept
                    codeableConcept={resource.priority}
                    name='Priority'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='priority'
                />
            }
            {
                resource.purpose &&
                <Partials.Code code={resource.purpose} name='Purpose'/>
            }
            {
                resource.patient !== undefined && resource.patient !== null &&
                <Partials.Reference
                    reference={resource.patient}
                    name='Patient'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='patient'
                />
            }
            {
                resource.servicedDate !== undefined && resource.servicedDate !== null &&
                <Partials.Date
                    date={resource.servicedDate}
                    name='Serviced Date'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='serviced-date'
                />
            }
            {
                resource.servicedPeriod !== undefined && resource.servicedPeriod !== null &&
                <Partials.Period
                    period={resource.servicedPeriod}
                    name='Serviced Period'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='serviced-period'
                />
            }
            {
                resource.created !== undefined && resource.created !== null &&
                <Partials.DateTime
                    dateTime={resource.created}
                    name='Created'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='created'
                />
            }
            {
                resource.enterer !== undefined && resource.enterer !== null &&
                <Partials.Reference
                    reference={resource.enterer}
                    name='Enterer'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='enterer'
                />
            }
            {
                resource.provider !== undefined && resource.provider !== null &&
                <Partials.Reference
                    reference={resource.provider}
                    name='Provider'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='provider'
                />
            }
            {
                resource.insurer !== undefined && resource.insurer !== null &&
                <Partials.Reference
                    reference={resource.insurer}
                    name='Insurer'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='insurer'
                />
            }
            {
                resource.facility !== undefined && resource.facility !== null &&
                <Partials.Reference
                    reference={resource.facility}
                    name='Facility'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='facility'
                />
            }
            {
                resource.supportingInfo !== undefined && resource.supportingInfo !== null &&
                <Partials.Reference
                    reference={resource.supportingInfo}
                    name='Supporting Info'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='supporting-info'
                    field='information'
                />
            }
            {
                resource.insurance !== undefined && resource.insurance !== null &&
                <Partials.Reference
                    reference={resource.insurance}
                    name='Insurance'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='insurance'
                    field='coverage'
                />
            }
            {
                resource.item !== undefined && resource.item !== null &&
                <Partials.CoverageEligibilityRequestItem
                    item={resource.item}
                    name='Item'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='item'
                    field=''
                />
            }
        </>
    );
};

export default CoverageEligibilityRequest;
