// This file is auto-generated by generate_components so do not edit manually

/**
Device
    A type of a manufactured item that is used in the provision of healthcare
    without being substantially changed through that activity. The device may be a
    medical or non-medical device.
    If the element is present, it must have either a @value, an @id, or extensions
*/

import React from 'react';
import { Link } from 'react-router';
import { TDevice } from '../../types/resources/Device';

// Import all the partial resource
import Partials from '../../partials';
import { IdentifierSystem } from '../../utils/identifierSystem';

const Device = ({ resource }: { resource: TDevice }): React.ReactElement => {
    const tagUUID = resource?.meta?.tag?.find((s) => s.system === IdentifierSystem.uuid)?.code;
    const uuid = tagUUID ? tagUUID : resource.id;

    return (
        <>
            <Link title="Direct link to Resource" to={`/4_0_0/${resource.resourceType}/${uuid}`}>
                {resource.resourceType}/{uuid}
            </Link>
            {
                resource.id &&
                <Partials.String
                    string={resource.id}
                    name='Id'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='id'
                />
            }
            {
                resource.meta &&
                <Partials.Meta
                    meta={resource.meta}
                    name='Meta'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='meta'
                />
            }
            {
                resource.implicitRules &&
                <Partials.Uri
                    uri={resource.implicitRules}
                    name='Implicit Rules'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='implicit-rules'
                />
            }
            {
                resource.language &&
                <Partials.Code code={resource.language} name='Language'/>
            }
            {
                resource.text &&
                <Partials.Narrative
                    narrative={resource.text}
                    name='Text'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='text'
                />
            }
            {
                resource.extension &&
                <Partials.Extension
                    extension={resource.extension}
                    name='Extension'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='extension'
                />
            }
            {
                resource.modifierExtension &&
                <Partials.Extension
                    extension={resource.modifierExtension}
                    name='Modifier Extension'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='modifier-extension'
                />
            }
            {
                resource.identifier &&
                <Partials.Identifier
                    identifier={resource.identifier}
                    name='Identifier'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='identifier'
                />
            }
            {
                resource.definition &&
                <Partials.Reference
                    reference={resource.definition}
                    name='Definition'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='definition'
                />
            }
            {
                resource.udiCarrier &&
                <Partials.DeviceUdiCarrier
                    udiCarrier={resource.udiCarrier}
                    name='Udi Carrier'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='udi-carrier'
                    field=''
                />
            }
            {
                resource.status &&
                <Partials.Code code={resource.status} name='Status'/>
            }
            {
                resource.statusReason &&
                <Partials.CodeableConcept
                    codeableConcept={resource.statusReason}
                    name='Status Reason'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='status-reason'
                />
            }
            {
                resource.distinctIdentifier &&
                <Partials.String
                    string={resource.distinctIdentifier}
                    name='Distinct Identifier'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='distinct-identifier'
                />
            }
            {
                resource.manufacturer &&
                <Partials.String
                    string={resource.manufacturer}
                    name='Manufacturer'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='manufacturer'
                />
            }
            {
                resource.manufactureDate &&
                <Partials.DateTime
                    dateTime={resource.manufactureDate}
                    name='Manufacture Date'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='manufacture-date'
                />
            }
            {
                resource.expirationDate &&
                <Partials.DateTime
                    dateTime={resource.expirationDate}
                    name='Expiration Date'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='expiration-date'
                />
            }
            {
                resource.lotNumber &&
                <Partials.String
                    string={resource.lotNumber}
                    name='Lot Number'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='lot-number'
                />
            }
            {
                resource.serialNumber &&
                <Partials.String
                    string={resource.serialNumber}
                    name='Serial Number'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='serial-number'
                />
            }
            {
                resource.deviceName &&
                <Partials.DeviceDeviceName
                    deviceName={resource.deviceName}
                    name='Device Name'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='device-name'
                    field=''
                />
            }
            {
                resource.modelNumber &&
                <Partials.String
                    string={resource.modelNumber}
                    name='Model Number'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='model-number'
                />
            }
            {
                resource.partNumber &&
                <Partials.String
                    string={resource.partNumber}
                    name='Part Number'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='part-number'
                />
            }
            {
                resource.type &&
                <Partials.CodeableConcept
                    codeableConcept={resource.type}
                    name='Type'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='type'
                />
            }
            {
                resource.patient &&
                <Partials.Reference
                    reference={resource.patient}
                    name='Patient'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='patient'
                />
            }
            {
                resource.owner &&
                <Partials.Reference
                    reference={resource.owner}
                    name='Owner'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='owner'
                />
            }
            {
                resource.contact &&
                <Partials.ContactPoint
                    contactPoint={resource.contact}
                    name='Contact'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='contact'
                />
            }
            {
                resource.location &&
                <Partials.Reference
                    reference={resource.location}
                    name='Location'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='location'
                />
            }
            {
                resource.url &&
                <Partials.Uri
                    uri={resource.url}
                    name='Url'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='url'
                />
            }
            {
                resource.note &&
                <Partials.Annotation
                    annotation={resource.note}
                    name='Note'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='note'
                />
            }
            {
                resource.safety &&
                <Partials.CodeableConcept
                    codeableConcept={resource.safety}
                    name='Safety'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='safety'
                />
            }
            {
                resource.parent &&
                <Partials.Reference
                    reference={resource.parent}
                    name='Parent'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='parent'
                />
            }
        </>
    );
};

export default Device;
