// This file is auto-generated by generate_components so do not edit manually

/**
DocumentReference
    A reference to a document of any kind for any purpose. Provides metadata about
    the document so that the document can be discovered and managed. The scope of
    a document is any seralized object with a mime-type, so includes formal
    patient centric documents (CDA), cliical notes, scanned paper, and non-patient
    specific documents like policy text.
    If the element is present, it must have either a @value, an @id, or extensions
*/

import React from 'react';
import { Link } from 'react-router';
import { TDocumentReference } from '../../types/resources/DocumentReference';

// Import all the partial resource
import Partials from '../../partials';
import { IdentifierSystem } from '../../utils/identifierSystem';

const DocumentReference = ({ resource }: { resource: TDocumentReference }): React.ReactElement => {
    const tagUUID = resource?.meta?.tag?.find((s) => s.system === IdentifierSystem.uuid)?.code;
    const uuid = tagUUID ? tagUUID : resource.id;

    return (
        <>
            <Link title="Direct link to Resource" to={`/4_0_0/${resource.resourceType}/${uuid}`}>
                {resource.resourceType}/{uuid}
            </Link>
            {
                resource.id !== undefined && resource.id !== null &&
                <Partials.String
                    string={resource.id}
                    name='Id'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='id'
                />
            }
            {
                resource.meta !== undefined && resource.meta !== null &&
                <Partials.Meta
                    meta={resource.meta}
                    name='Meta'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='meta'
                />
            }
            {
                resource.implicitRules !== undefined && resource.implicitRules !== null &&
                <Partials.Uri
                    uri={resource.implicitRules}
                    name='Implicit Rules'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='implicit-rules'
                />
            }
            {
                resource.language &&
                <Partials.Code code={resource.language} name='Language'/>
            }
            {
                resource.text !== undefined && resource.text !== null &&
                <Partials.Narrative
                    narrative={resource.text}
                    name='Text'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='text'
                />
            }
            {
                resource.extension !== undefined && resource.extension !== null &&
                <Partials.Extension
                    extension={resource.extension}
                    name='Extension'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='extension'
                />
            }
            {
                resource.modifierExtension !== undefined && resource.modifierExtension !== null &&
                <Partials.Extension
                    extension={resource.modifierExtension}
                    name='Modifier Extension'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='modifier-extension'
                />
            }
            {
                resource.masterIdentifier !== undefined && resource.masterIdentifier !== null &&
                <Partials.Identifier
                    identifier={resource.masterIdentifier}
                    name='Master Identifier'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='master-identifier'
                />
            }
            {
                resource.identifier !== undefined && resource.identifier !== null &&
                <Partials.Identifier
                    identifier={resource.identifier}
                    name='Identifier'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='identifier'
                />
            }
            {
                resource.status &&
                <Partials.Code code={resource.status} name='Status'/>
            }
            {
                resource.docStatus &&
                <Partials.Code code={resource.docStatus} name='Doc Status'/>
            }
            {
                resource.type !== undefined && resource.type !== null &&
                <Partials.CodeableConcept
                    codeableConcept={resource.type}
                    name='Type'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='type'
                />
            }
            {
                resource.category !== undefined && resource.category !== null &&
                <Partials.CodeableConcept
                    codeableConcept={resource.category}
                    name='Category'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='category'
                />
            }
            {
                resource.subject !== undefined && resource.subject !== null &&
                <Partials.Reference
                    reference={resource.subject}
                    name='Subject'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='subject'
                />
            }
            {
                resource.date !== undefined && resource.date !== null &&
                <Partials.Instant
                    instant={resource.date}
                    name='Date'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='date'
                />
            }
            {
                resource.author !== undefined && resource.author !== null &&
                <Partials.Reference
                    reference={resource.author}
                    name='Author'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='author'
                />
            }
            {
                resource.authenticator !== undefined && resource.authenticator !== null &&
                <Partials.Reference
                    reference={resource.authenticator}
                    name='Authenticator'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='authenticator'
                />
            }
            {
                resource.custodian !== undefined && resource.custodian !== null &&
                <Partials.Reference
                    reference={resource.custodian}
                    name='Custodian'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='custodian'
                />
            }
            {
                resource.relatesTo !== undefined && resource.relatesTo !== null &&
                <Partials.DocumentReferenceRelatesTo
                    relatesTo={resource.relatesTo}
                    name='Relates To'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='relates-to'
                    field=''
                />
            }
            {
                resource.description !== undefined && resource.description !== null &&
                <Partials.String
                    string={resource.description}
                    name='Description'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='description'
                />
            }
            {
                resource.securityLabel !== undefined && resource.securityLabel !== null &&
                <Partials.CodeableConcept
                    codeableConcept={resource.securityLabel}
                    name='Security Label'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='security-label'
                />
            }
            {
                resource.content !== undefined && resource.content !== null &&
                <Partials.DocumentContent
                    content={resource.content}
                    name='Content'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='content'
                    field=''
                />
            }
            {
                resource.context !== undefined && resource.context !== null &&
                <Partials.DocumentReferenceContext
                    context={resource.context}
                    name='Context'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='context'
                    field=''
                />
            }
        </>
    );
};

export default DocumentReference;
