// This file is auto-generated by generate_components so do not edit manually

/**
Encounter
    An interaction between a patient and healthcare provider(s) for the purpose of
    providing healthcare service(s) or assessing the health status of a patient.
    If the element is present, it must have either a @value, an @id, or extensions
*/

import React from 'react';
import { Link } from 'react-router';
import { Typography } from '@mui/material';
import { TEncounter } from '../../types/resources/Encounter';

// Import all the partial resource
import Partials from '../../partials';
import { IdentifierSystem } from '../../utils/identifierSystem';

const Encounter = ({ resource }: { resource: TEncounter }): React.ReactElement => {
    const tagUUID = resource?.meta?.tag?.find((s) => s.system === IdentifierSystem.uuid)?.code;
    const uuid = tagUUID ? tagUUID : resource.id;

    return (
        <>
            <Link title="Direct link to Resource" to={`/4_0_0/${resource.resourceType}/${uuid}`}>
                {resource.resourceType}/{uuid}
            </Link>
            {
                resource.id !== undefined && resource.id !== null &&
                <Partials.String
                    string={resource.id}
                    name='Id'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='id'
                />
            }
            {
                resource.meta !== undefined && resource.meta !== null &&
                <Partials.Meta
                    meta={resource.meta}
                    name='Meta'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='meta'
                />
            }
            {
                resource.implicitRules !== undefined && resource.implicitRules !== null &&
                <Partials.Uri
                    uri={resource.implicitRules}
                    name='Implicit Rules'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='implicit-rules'
                />
            }
            {
                resource.language &&
                <Partials.Code code={resource.language} name='Language'/>
            }
            {
                resource.text !== undefined && resource.text !== null &&
                <Partials.Narrative
                    narrative={resource.text}
                    name='Text'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='text'
                />
            }
            {
                resource.extension !== undefined && resource.extension !== null &&
                <Partials.Extension
                    extension={resource.extension}
                    name='Extension'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='extension'
                />
            }
            {
                resource.modifierExtension !== undefined && resource.modifierExtension !== null &&
                <Partials.Extension
                    extension={resource.modifierExtension}
                    name='Modifier Extension'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='modifier-extension'
                />
            }
            {
                resource.identifier !== undefined && resource.identifier !== null &&
                <Partials.Identifier
                    identifier={resource.identifier}
                    name='Identifier'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='identifier'
                />
            }
            {
                resource.status &&
                <Partials.Code code={resource.status} name='Status'/>
            }
            {
                resource.statusHistory !== undefined && resource.statusHistory !== null &&
                <Partials.EncounterStatusHistory
                    statusHistory={resource.statusHistory}
                    name='Status History'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='status-history'
                    field=''
                />
            }
            {
                resource.class_ !== undefined && resource.class_ !== null &&
                <Partials.Coding
                    coding={resource.class_}
                    name='Class_'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='class_'
                />
            }
            {
                resource.classHistory !== undefined && resource.classHistory !== null &&
                <Partials.EncounterClassHistory
                    classHistory={resource.classHistory}
                    name='Class History'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='class-history'
                    field=''
                />
            }
            {
                resource.type !== undefined && resource.type !== null &&
                <Partials.CodeableConcept
                    codeableConcept={resource.type}
                    name='Type'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='type'
                />
            }
            {
                resource.serviceType !== undefined && resource.serviceType !== null &&
                <Partials.CodeableConcept
                    codeableConcept={resource.serviceType}
                    name='Service Type'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='service-type'
                />
            }
            {
                resource.priority !== undefined && resource.priority !== null &&
                <Partials.CodeableConcept
                    codeableConcept={resource.priority}
                    name='Priority'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='priority'
                />
            }
            {
                resource.subject !== undefined && resource.subject !== null &&
                <Partials.Reference
                    reference={resource.subject}
                    name='Subject'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='subject'
                />
            }
            {
                resource.episodeOfCare !== undefined && resource.episodeOfCare !== null &&
                <Partials.Reference
                    reference={resource.episodeOfCare}
                    name='Episode Of Care'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='episode-of-care'
                />
            }
            {
                resource.basedOn !== undefined && resource.basedOn !== null &&
                <Partials.Reference
                    reference={resource.basedOn}
                    name='Based On'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='based-on'
                />
            }
            {
                resource.participant !== undefined && resource.participant !== null &&
                <Partials.EncounterParticipant
                    participant={resource.participant}
                    name='Participant'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='participant'
                    field=''
                />
            }
            {
                resource.appointment !== undefined && resource.appointment !== null &&
                <Partials.Reference
                    reference={resource.appointment}
                    name='Appointment'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='appointment'
                />
            }
            {
                resource.period !== undefined && resource.period !== null &&
                <Partials.Period
                    period={resource.period}
                    name='Period'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='period'
                />
            }
            {
                resource.length !== undefined && resource.length !== null &&
                <Partials.Quantity
                    quantity={resource.length}
                    name='Length'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='length'
                />
            }
            {
                resource.reasonCode !== undefined && resource.reasonCode !== null &&
                <Partials.CodeableConcept
                    codeableConcept={resource.reasonCode}
                    name='Reason Code'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='reason-code'
                />
            }
            {
                resource.reasonReference !== undefined && resource.reasonReference !== null &&
                <Partials.Reference
                    reference={resource.reasonReference}
                    name='Reason Reference'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='reason-reference'
                />
            }
            {
                resource.diagnosis !== undefined && resource.diagnosis !== null &&
                <Partials.EncounterDiagnosis
                    diagnosis={resource.diagnosis}
                    name='Diagnosis'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='diagnosis'
                    field=''
                />
            }
            {
                resource.account !== undefined && resource.account !== null &&
                <Partials.Reference
                    reference={resource.account}
                    name='Account'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='account'
                />
            }
            {
                resource.hospitalization !== undefined && resource.hospitalization !== null &&
                <Partials.EncounterHospitalization
                    hospitalization={resource.hospitalization}
                    name='Hospitalization'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='hospitalization'
                    field=''
                />
            }
            {
                resource.location !== undefined && resource.location !== null &&
                <Partials.EncounterLocation
                    location={resource.location}
                    name='Location'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='location'
                    field=''
                />
            }
            {
                resource.serviceProvider !== undefined && resource.serviceProvider !== null &&
                <Partials.Reference
                    reference={resource.serviceProvider}
                    name='Service Provider'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='service-provider'
                />
            }
            {
                resource.partOf !== undefined && resource.partOf !== null &&
                <Partials.Reference
                    reference={resource.partOf}
                    name='Part Of'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='part-of'
                />
            }
            <Typography variant="h6" color="text.secondary" sx={{ mt: 1 }}>
                Related Resources
            </Typography>
            <Partials.ReverseReference
                name="DocumentReference"
                id={uuid}
                resourceType={resource.resourceType}
                reverseReferences={[{'target': 'DocumentReference', 'property': 'encounter'}]}
            />
        </>
    );
};

export default Encounter;
