// This file is auto-generated by generate_components so do not edit manually

/**
Evidence
    The Evidence Resource provides a machine-interpretable expression of an
    evidence concept including the evidence variables (eg population,
    exposures/interventions, comparators, outcomes, measured variables,
    confounding variables), the statistics, and the certainty of this evidence.
    If the element is present, it must have either a @value, an @id, or extensions
*/

import React from 'react';
import { Link } from 'react-router';
import { TEvidence } from '../../types/resources/Evidence';

// Import all the partial resource
import Partials from '../../partials';
import { IdentifierSystem } from '../../utils/identifierSystem';

const Evidence = ({ resource }: { resource: TEvidence }): React.ReactElement => {
    const tagUUID = resource?.meta?.tag?.find((s) => s.system === IdentifierSystem.uuid)?.code;
    const uuid = tagUUID ? tagUUID : resource.id;

    return (
        <>
            <Link title="Direct link to Resource" to={`/4_0_0/${resource.resourceType}/${uuid}`}>
                {resource.resourceType}/{uuid}
            </Link>
            {
                resource.id !== undefined && resource.id !== null &&
                <Partials.String
                    string={resource.id}
                    name='Id'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='id'
                />
            }
            {
                resource.meta !== undefined && resource.meta !== null &&
                <Partials.Meta
                    meta={resource.meta}
                    name='Meta'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='meta'
                />
            }
            {
                resource.implicitRules !== undefined && resource.implicitRules !== null &&
                <Partials.Uri
                    uri={resource.implicitRules}
                    name='Implicit Rules'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='implicit-rules'
                />
            }
            {
                resource.language &&
                <Partials.Code code={resource.language} name='Language'/>
            }
            {
                resource.text !== undefined && resource.text !== null &&
                <Partials.Narrative
                    narrative={resource.text}
                    name='Text'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='text'
                />
            }
            {
                resource.extension !== undefined && resource.extension !== null &&
                <Partials.Extension
                    extension={resource.extension}
                    name='Extension'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='extension'
                />
            }
            {
                resource.modifierExtension !== undefined && resource.modifierExtension !== null &&
                <Partials.Extension
                    extension={resource.modifierExtension}
                    name='Modifier Extension'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='modifier-extension'
                />
            }
            {
                resource.url !== undefined && resource.url !== null &&
                <Partials.Uri
                    uri={resource.url}
                    name='Url'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='url'
                />
            }
            {
                resource.identifier !== undefined && resource.identifier !== null &&
                <Partials.Identifier
                    identifier={resource.identifier}
                    name='Identifier'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='identifier'
                />
            }
            {
                resource.version !== undefined && resource.version !== null &&
                <Partials.String
                    string={resource.version}
                    name='Version'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='version'
                />
            }
            {
                resource.title !== undefined && resource.title !== null &&
                <Partials.String
                    string={resource.title}
                    name='Title'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='title'
                />
            }
            {
                resource.citeAsReference !== undefined && resource.citeAsReference !== null &&
                <Partials.Reference
                    reference={resource.citeAsReference}
                    name='Cite As Reference'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='cite-as-reference'
                />
            }
            {
                resource.citeAsMarkdown !== undefined && resource.citeAsMarkdown !== null &&
                <Partials.Markdown
                    markdown={resource.citeAsMarkdown}
                    name='Cite As Markdown'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='cite-as-markdown'
                />
            }
            {
                resource.status &&
                <Partials.Code code={resource.status} name='Status'/>
            }
            {
                resource.date !== undefined && resource.date !== null &&
                <Partials.DateTime
                    dateTime={resource.date}
                    name='Date'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='date'
                />
            }
            {
                resource.approvalDate !== undefined && resource.approvalDate !== null &&
                <Partials.Date
                    date={resource.approvalDate}
                    name='Approval Date'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='approval-date'
                />
            }
            {
                resource.lastReviewDate !== undefined && resource.lastReviewDate !== null &&
                <Partials.Date
                    date={resource.lastReviewDate}
                    name='Last Review Date'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='last-review-date'
                />
            }
            {
                resource.publisher !== undefined && resource.publisher !== null &&
                <Partials.String
                    string={resource.publisher}
                    name='Publisher'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='publisher'
                />
            }
            {
                resource.relatedArtifact !== undefined && resource.relatedArtifact !== null &&
                <Partials.RelatedArtifact
                    relatedArtifact={resource.relatedArtifact}
                    name='Related Artifact'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='related-artifact'
                />
            }
            {
                resource.description !== undefined && resource.description !== null &&
                <Partials.Markdown
                    markdown={resource.description}
                    name='Description'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='description'
                />
            }
            {
                resource.assertion !== undefined && resource.assertion !== null &&
                <Partials.Markdown
                    markdown={resource.assertion}
                    name='Assertion'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='assertion'
                />
            }
            {
                resource.note !== undefined && resource.note !== null &&
                <Partials.Annotation
                    annotation={resource.note}
                    name='Note'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='note'
                />
            }
            {
                resource.variableDefinition !== undefined && resource.variableDefinition !== null &&
                <Partials.EvidenceVariableDefinition
                    variableDefinition={resource.variableDefinition}
                    name='Variable Definition'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='variable-definition'
                    field=''
                />
            }
            {
                resource.synthesisType !== undefined && resource.synthesisType !== null &&
                <Partials.CodeableConcept
                    codeableConcept={resource.synthesisType}
                    name='Synthesis Type'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='synthesis-type'
                />
            }
            {
                resource.studyType !== undefined && resource.studyType !== null &&
                <Partials.CodeableConcept
                    codeableConcept={resource.studyType}
                    name='Study Type'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='study-type'
                />
            }
            {
                resource.statistic !== undefined && resource.statistic !== null &&
                <Partials.EvidenceStatistic
                    statistic={resource.statistic}
                    name='Statistic'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='statistic'
                    field=''
                />
            }
            {
                resource.certainty !== undefined && resource.certainty !== null &&
                <Partials.EvidenceCertainty
                    certainty={resource.certainty}
                    name='Certainty'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='certainty'
                    field=''
                />
            }
        </>
    );
};

export default Evidence;
