// This file is auto-generated by generate_components so do not edit manually

/**
ExampleScenario
    Example of workflow instance.
    If the element is present, it must have either a @value, an @id, or extensions
*/

import React from 'react';
import { Link } from 'react-router';
import { TExampleScenario } from '../../types/resources/ExampleScenario';

// Import all the partial resource
import Partials from '../../partials';
import { IdentifierSystem } from '../../utils/identifierSystem';

const ExampleScenario = ({ resource }: { resource: TExampleScenario }): React.ReactElement => {
    const tagUUID = resource?.meta?.tag?.find((s) => s.system === IdentifierSystem.uuid)?.code;
    const uuid = tagUUID ? tagUUID : resource.id;

    return (
        <>
            <Link title="Direct link to Resource" to={`/4_0_0/${resource.resourceType}/${uuid}`}>
                {resource.resourceType}/{uuid}
            </Link>
            {
                resource.id &&
                <Partials.String
                    string={resource.id}
                    name='Id'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='id'
                />
            }
            {
                resource.meta &&
                <Partials.Meta
                    meta={resource.meta}
                    name='Meta'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='meta'
                />
            }
            {
                resource.implicitRules &&
                <Partials.Uri
                    uri={resource.implicitRules}
                    name='Implicit Rules'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='implicit-rules'
                />
            }
            {
                resource.language &&
                <Partials.Code code={resource.language} name='Language'/>
            }
            {
                resource.text &&
                <Partials.Narrative
                    narrative={resource.text}
                    name='Text'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='text'
                />
            }
            {
                resource.extension &&
                <Partials.Extension
                    extension={resource.extension}
                    name='Extension'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='extension'
                />
            }
            {
                resource.modifierExtension &&
                <Partials.Extension
                    extension={resource.modifierExtension}
                    name='Modifier Extension'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='modifier-extension'
                />
            }
            {
                resource.url &&
                <Partials.Uri
                    uri={resource.url}
                    name='Url'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='url'
                />
            }
            {
                resource.identifier &&
                <Partials.Identifier
                    identifier={resource.identifier}
                    name='Identifier'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='identifier'
                />
            }
            {
                resource.version &&
                <Partials.String
                    string={resource.version}
                    name='Version'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='version'
                />
            }
            {
                resource.name &&
                <Partials.String
                    string={resource.name}
                    name='Name'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='name'
                />
            }
            {
                resource.status &&
                <Partials.Code code={resource.status} name='Status'/>
            }
            {
                resource.experimental &&
                <Partials.Boolean
                    boolean={resource.experimental}
                    name='Experimental'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='experimental'
                />
            }
            {
                resource.date &&
                <Partials.DateTime
                    dateTime={resource.date}
                    name='Date'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='date'
                />
            }
            {
                resource.publisher &&
                <Partials.String
                    string={resource.publisher}
                    name='Publisher'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='publisher'
                />
            }
            {
                resource.jurisdiction &&
                <Partials.CodeableConcept
                    codeableConcept={resource.jurisdiction}
                    name='Jurisdiction'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='jurisdiction'
                />
            }
            {
                resource.copyright &&
                <Partials.Markdown
                    markdown={resource.copyright}
                    name='Copyright'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='copyright'
                />
            }
            {
                resource.purpose &&
                <Partials.Markdown
                    markdown={resource.purpose}
                    name='Purpose'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='purpose'
                />
            }
            {
                resource.actor &&
                <Partials.ExampleScenarioActor
                    actor={resource.actor}
                    name='Actor'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='actor'
                    field=''
                />
            }
            {
                resource.instance &&
                <Partials.ExampleScenarioInstance
                    instance={resource.instance}
                    name='Instance'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='instance'
                    field=''
                />
            }
            {
                resource.process &&
                <Partials.ExampleScenarioProcess
                    process={resource.process}
                    name='Process'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='process'
                    field=''
                />
            }
            {
                resource.workflow &&
                <Partials.Canonical
                    canonical={resource.workflow}
                    name='Workflow'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='workflow'
                />
            }
        </>
    );
};

export default ExampleScenario;
