// This file is auto-generated by generate_components so do not edit manually

/**
ExplanationOfBenefit
    This resource provides: the claim details; adjudication details from the
    processing of a Claim; and optionally account balance information, for
    informing the subscriber of the benefits provided.
    If the element is present, it must have either a @value, an @id, or extensions
*/

import React from 'react';
import { Link } from 'react-router';
import { TExplanationOfBenefit } from '../../types/resources/ExplanationOfBenefit';

// Import all the partial resource
import Partials from '../../partials';
import { IdentifierSystem } from '../../utils/identifierSystem';

const ExplanationOfBenefit = ({ resource }: { resource: TExplanationOfBenefit }): React.ReactElement => {
    const tagUUID = resource?.meta?.tag?.find((s) => s.system === IdentifierSystem.uuid)?.code;
    const uuid = tagUUID ? tagUUID : resource.id;

    return (
        <>
            <Link title="Direct link to Resource" to={`/4_0_0/${resource.resourceType}/${uuid}`}>
                {resource.resourceType}/{uuid}
            </Link>
            {
                resource.id !== undefined && resource.id !== null &&
                <Partials.String
                    string={resource.id}
                    name='Id'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='id'
                />
            }
            {
                resource.meta !== undefined && resource.meta !== null &&
                <Partials.Meta
                    meta={resource.meta}
                    name='Meta'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='meta'
                />
            }
            {
                resource.implicitRules !== undefined && resource.implicitRules !== null &&
                <Partials.Uri
                    uri={resource.implicitRules}
                    name='Implicit Rules'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='implicit-rules'
                />
            }
            {
                resource.language &&
                <Partials.Code code={resource.language} name='Language'/>
            }
            {
                resource.text !== undefined && resource.text !== null &&
                <Partials.Narrative
                    narrative={resource.text}
                    name='Text'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='text'
                />
            }
            {
                resource.extension !== undefined && resource.extension !== null &&
                <Partials.Extension
                    extension={resource.extension}
                    name='Extension'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='extension'
                />
            }
            {
                resource.modifierExtension !== undefined && resource.modifierExtension !== null &&
                <Partials.Extension
                    extension={resource.modifierExtension}
                    name='Modifier Extension'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='modifier-extension'
                />
            }
            {
                resource.identifier !== undefined && resource.identifier !== null &&
                <Partials.Identifier
                    identifier={resource.identifier}
                    name='Identifier'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='identifier'
                />
            }
            {
                resource.status &&
                <Partials.Code code={resource.status} name='Status'/>
            }
            {
                resource.type !== undefined && resource.type !== null &&
                <Partials.CodeableConcept
                    codeableConcept={resource.type}
                    name='Type'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='type'
                />
            }
            {
                resource.subType !== undefined && resource.subType !== null &&
                <Partials.CodeableConcept
                    codeableConcept={resource.subType}
                    name='Sub Type'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='sub-type'
                />
            }
            {
                resource.use &&
                <Partials.Code code={resource.use} name='Use'/>
            }
            {
                resource.patient !== undefined && resource.patient !== null &&
                <Partials.Reference
                    reference={resource.patient}
                    name='Patient'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='patient'
                />
            }
            {
                resource.billablePeriod !== undefined && resource.billablePeriod !== null &&
                <Partials.Period
                    period={resource.billablePeriod}
                    name='Billable Period'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='billable-period'
                />
            }
            {
                resource.created !== undefined && resource.created !== null &&
                <Partials.DateTime
                    dateTime={resource.created}
                    name='Created'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='created'
                />
            }
            {
                resource.enterer !== undefined && resource.enterer !== null &&
                <Partials.Reference
                    reference={resource.enterer}
                    name='Enterer'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='enterer'
                />
            }
            {
                resource.insurer !== undefined && resource.insurer !== null &&
                <Partials.Reference
                    reference={resource.insurer}
                    name='Insurer'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='insurer'
                />
            }
            {
                resource.provider !== undefined && resource.provider !== null &&
                <Partials.Reference
                    reference={resource.provider}
                    name='Provider'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='provider'
                />
            }
            {
                resource.priority !== undefined && resource.priority !== null &&
                <Partials.CodeableConcept
                    codeableConcept={resource.priority}
                    name='Priority'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='priority'
                />
            }
            {
                resource.fundsReserveRequested !== undefined && resource.fundsReserveRequested !== null &&
                <Partials.CodeableConcept
                    codeableConcept={resource.fundsReserveRequested}
                    name='Funds Reserve Requested'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='funds-reserve-requested'
                />
            }
            {
                resource.fundsReserve !== undefined && resource.fundsReserve !== null &&
                <Partials.CodeableConcept
                    codeableConcept={resource.fundsReserve}
                    name='Funds Reserve'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='funds-reserve'
                />
            }
            {
                resource.prescription !== undefined && resource.prescription !== null &&
                <Partials.Reference
                    reference={resource.prescription}
                    name='Prescription'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='prescription'
                />
            }
            {
                resource.originalPrescription !== undefined && resource.originalPrescription !== null &&
                <Partials.Reference
                    reference={resource.originalPrescription}
                    name='Original Prescription'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='original-prescription'
                />
            }
            {
                resource.payee !== undefined && resource.payee !== null &&
                <Partials.ExplanationOfBenefitPayee
                    payee={resource.payee}
                    name='Payee'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='payee'
                    field=''
                />
            }
            {
                resource.referral !== undefined && resource.referral !== null &&
                <Partials.Reference
                    reference={resource.referral}
                    name='Referral'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='referral'
                />
            }
            {
                resource.facility !== undefined && resource.facility !== null &&
                <Partials.Reference
                    reference={resource.facility}
                    name='Facility'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='facility'
                />
            }
            {
                resource.claim !== undefined && resource.claim !== null &&
                <Partials.Reference
                    reference={resource.claim}
                    name='Claim'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='claim'
                />
            }
            {
                resource.claimResponse !== undefined && resource.claimResponse !== null &&
                <Partials.Reference
                    reference={resource.claimResponse}
                    name='Claim Response'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='claim-response'
                />
            }
            {
                resource.outcome &&
                <Partials.Code code={resource.outcome} name='Outcome'/>
            }
            {
                resource.disposition !== undefined && resource.disposition !== null &&
                <Partials.String
                    string={resource.disposition}
                    name='Disposition'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='disposition'
                />
            }
            {
                resource.preAuthRef !== undefined && resource.preAuthRef !== null &&
                <Partials.String
                    string={resource.preAuthRef}
                    name='Pre Auth Ref'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='pre-auth-ref'
                />
            }
            {
                resource.preAuthRefPeriod !== undefined && resource.preAuthRefPeriod !== null &&
                <Partials.Period
                    period={resource.preAuthRefPeriod}
                    name='Pre Auth Ref Period'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='pre-auth-ref-period'
                />
            }
            {
                resource.careTeam !== undefined && resource.careTeam !== null &&
                <Partials.Reference
                    reference={resource.careTeam}
                    name='Care Team'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='care-team'
                    field='provider'
                />
            }
            {
                resource.diagnosis !== undefined && resource.diagnosis !== null &&
                <Partials.ExplanationOfBenefitDiagnosis
                    diagnosis={resource.diagnosis}
                    name='Diagnosis'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='diagnosis'
                    field=''
                />
            }
            {
                resource.precedence !== undefined && resource.precedence !== null &&
                <Partials.Int
                    int={resource.precedence}
                    name='Precedence'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='precedence'
                />
            }
            {
                resource.insurance !== undefined && resource.insurance !== null &&
                <Partials.Reference
                    reference={resource.insurance}
                    name='Insurance'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='insurance'
                    field='coverage'
                />
            }
            {
                resource.item !== undefined && resource.item !== null &&
                <Partials.ExplanationOfBenefitItem
                    item={resource.item}
                    name='Item'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='item'
                    field=''
                />
            }
            {
                resource.adjudication !== undefined && resource.adjudication !== null &&
                <Partials.ExplanationOfBenefitAdjudication
                    adjudication={resource.adjudication}
                    name='Adjudication'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='adjudication'
                    field=''
                />
            }
            {
                resource.total !== undefined && resource.total !== null &&
                <Partials.ExplanationOfBenefitTotal
                    total={resource.total}
                    name='Total'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='total'
                    field=''
                />
            }
            {
                resource.payment !== undefined && resource.payment !== null &&
                <Partials.ExplanationOfBenefitPayment
                    payment={resource.payment}
                    name='Payment'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='payment'
                    field=''
                />
            }
            {
                resource.formCode !== undefined && resource.formCode !== null &&
                <Partials.CodeableConcept
                    codeableConcept={resource.formCode}
                    name='Form Code'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='form-code'
                />
            }
            {
                resource.form !== undefined && resource.form !== null &&
                <Partials.Attachment
                    attachment={resource.form}
                    name='Form'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='form'
                />
            }
            {
                resource.processNote !== undefined && resource.processNote !== null &&
                <Partials.ExplanationOfBenefitProcessNote
                    processNote={resource.processNote}
                    name='Process Note'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='process-note'
                    field=''
                />
            }
            {
                resource.benefitPeriod !== undefined && resource.benefitPeriod !== null &&
                <Partials.Period
                    period={resource.benefitPeriod}
                    name='Benefit Period'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='benefit-period'
                />
            }
            {
                resource.benefitBalance !== undefined && resource.benefitBalance !== null &&
                <Partials.ExplanationOfBenefitBenefitBalance
                    benefitBalance={resource.benefitBalance}
                    name='Benefit Balance'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='benefit-balance'
                    field=''
                />
            }
        </>
    );
};

export default ExplanationOfBenefit;
