// This file is auto-generated by generate_components so do not edit manually

/**
ImagingStudy
    Representation of the content produced in a DICOM imaging study. A study
    comprises a set of series, each of which includes a set of Service-Object Pair
    Instances (SOP Instances - images or other data) acquired or produced in a
    common context.  A series is of only one modality (e.g. X-ray, CT, MR,
    ultrasound), but a study may have multiple series of different modalities.
    If the element is present, it must have either a @value, an @id, or extensions
*/

import React from 'react';
import { Link } from 'react-router';
import { TImagingStudy } from '../../types/resources/ImagingStudy';

// Import all the partial resource
import Partials from '../../partials';
import { IdentifierSystem } from '../../utils/identifierSystem';

const ImagingStudy = ({ resource }: { resource: TImagingStudy }): React.ReactElement => {
    const tagUUID = resource?.meta?.tag?.find((s) => s.system === IdentifierSystem.uuid)?.code;
    const uuid = tagUUID ? tagUUID : resource.id;

    return (
        <>
            <Link title="Direct link to Resource" to={`/4_0_0/${resource.resourceType}/${uuid}`}>
                {resource.resourceType}/{uuid}
            </Link>
            {
                resource.id !== undefined && resource.id !== null &&
                <Partials.String
                    string={resource.id}
                    name='Id'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='id'
                />
            }
            {
                resource.meta !== undefined && resource.meta !== null &&
                <Partials.Meta
                    meta={resource.meta}
                    name='Meta'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='meta'
                />
            }
            {
                resource.implicitRules !== undefined && resource.implicitRules !== null &&
                <Partials.Uri
                    uri={resource.implicitRules}
                    name='Implicit Rules'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='implicit-rules'
                />
            }
            {
                resource.language &&
                <Partials.Code code={resource.language} name='Language'/>
            }
            {
                resource.text !== undefined && resource.text !== null &&
                <Partials.Narrative
                    narrative={resource.text}
                    name='Text'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='text'
                />
            }
            {
                resource.extension !== undefined && resource.extension !== null &&
                <Partials.Extension
                    extension={resource.extension}
                    name='Extension'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='extension'
                />
            }
            {
                resource.modifierExtension !== undefined && resource.modifierExtension !== null &&
                <Partials.Extension
                    extension={resource.modifierExtension}
                    name='Modifier Extension'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='modifier-extension'
                />
            }
            {
                resource.identifier !== undefined && resource.identifier !== null &&
                <Partials.Identifier
                    identifier={resource.identifier}
                    name='Identifier'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='identifier'
                />
            }
            {
                resource.status &&
                <Partials.Code code={resource.status} name='Status'/>
            }
            {
                resource.modality !== undefined && resource.modality !== null &&
                <Partials.Coding
                    coding={resource.modality}
                    name='Modality'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='modality'
                />
            }
            {
                resource.subject !== undefined && resource.subject !== null &&
                <Partials.Reference
                    reference={resource.subject}
                    name='Subject'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='subject'
                />
            }
            {
                resource.encounter !== undefined && resource.encounter !== null &&
                <Partials.Reference
                    reference={resource.encounter}
                    name='Encounter'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='encounter'
                />
            }
            {
                resource.started !== undefined && resource.started !== null &&
                <Partials.DateTime
                    dateTime={resource.started}
                    name='Started'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='started'
                />
            }
            {
                resource.basedOn !== undefined && resource.basedOn !== null &&
                <Partials.Reference
                    reference={resource.basedOn}
                    name='Based On'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='based-on'
                />
            }
            {
                resource.referrer !== undefined && resource.referrer !== null &&
                <Partials.Reference
                    reference={resource.referrer}
                    name='Referrer'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='referrer'
                />
            }
            {
                resource.interpreter !== undefined && resource.interpreter !== null &&
                <Partials.Reference
                    reference={resource.interpreter}
                    name='Interpreter'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='interpreter'
                />
            }
            {
                resource.endpoint !== undefined && resource.endpoint !== null &&
                <Partials.Reference
                    reference={resource.endpoint}
                    name='Endpoint'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='endpoint'
                />
            }
            {
                resource.numberOfSeries !== undefined && resource.numberOfSeries !== null &&
                <Partials.UnsignedInt
                    unsignedInt={resource.numberOfSeries}
                    name='Number Of Series'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='number-of-series'
                />
            }
            {
                resource.numberOfInstances !== undefined && resource.numberOfInstances !== null &&
                <Partials.UnsignedInt
                    unsignedInt={resource.numberOfInstances}
                    name='Number Of Instances'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='number-of-instances'
                />
            }
            {
                resource.procedureReference !== undefined && resource.procedureReference !== null &&
                <Partials.Reference
                    reference={resource.procedureReference}
                    name='Procedure Reference'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='procedure-reference'
                />
            }
            {
                resource.procedureCode !== undefined && resource.procedureCode !== null &&
                <Partials.CodeableConcept
                    codeableConcept={resource.procedureCode}
                    name='Procedure Code'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='procedure-code'
                />
            }
            {
                resource.location !== undefined && resource.location !== null &&
                <Partials.Reference
                    reference={resource.location}
                    name='Location'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='location'
                />
            }
            {
                resource.reasonCode !== undefined && resource.reasonCode !== null &&
                <Partials.CodeableConcept
                    codeableConcept={resource.reasonCode}
                    name='Reason Code'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='reason-code'
                />
            }
            {
                resource.reasonReference !== undefined && resource.reasonReference !== null &&
                <Partials.Reference
                    reference={resource.reasonReference}
                    name='Reason Reference'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='reason-reference'
                />
            }
            {
                resource.note !== undefined && resource.note !== null &&
                <Partials.Annotation
                    annotation={resource.note}
                    name='Note'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='note'
                />
            }
            {
                resource.description !== undefined && resource.description !== null &&
                <Partials.String
                    string={resource.description}
                    name='Description'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='description'
                />
            }
            {
                resource.series !== undefined && resource.series !== null &&
                <Partials.ImagingStudySeries
                    series={resource.series}
                    name='Series'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='series'
                    field=''
                />
            }
        </>
    );
};

export default ImagingStudy;
