// This file is auto-generated by generate_components so do not edit manually

/**
ManufacturedItemDefinition
    The definition and characteristics of a medicinal manufactured item, such as a
    tablet or capsule, as contained in a packaged medicinal product.
    If the element is present, it must have either a @value, an @id, or extensions
*/

import React from 'react';
import { Link } from 'react-router';
import { TManufacturedItemDefinition } from '../../types/resources/ManufacturedItemDefinition';

// Import all the partial resource
import Partials from '../../partials';
import { IdentifierSystem } from '../../utils/identifierSystem';

const ManufacturedItemDefinition = ({ resource }: { resource: TManufacturedItemDefinition }): React.ReactElement => {
    const tagUUID = resource?.meta?.tag?.find((s) => s.system === IdentifierSystem.uuid)?.code;
    const uuid = tagUUID ? tagUUID : resource.id;

    return (
        <>
            <Link title="Direct link to Resource" to={`/4_0_0/${resource.resourceType}/${uuid}`}>
                {resource.resourceType}/{uuid}
            </Link>
            {
                resource.id !== undefined && resource.id !== null &&
                <Partials.String
                    string={resource.id}
                    name='Id'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='id'
                />
            }
            {
                resource.meta !== undefined && resource.meta !== null &&
                <Partials.Meta
                    meta={resource.meta}
                    name='Meta'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='meta'
                />
            }
            {
                resource.implicitRules !== undefined && resource.implicitRules !== null &&
                <Partials.Uri
                    uri={resource.implicitRules}
                    name='Implicit Rules'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='implicit-rules'
                />
            }
            {
                resource.language &&
                <Partials.Code code={resource.language} name='Language'/>
            }
            {
                resource.text !== undefined && resource.text !== null &&
                <Partials.Narrative
                    narrative={resource.text}
                    name='Text'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='text'
                />
            }
            {
                resource.extension !== undefined && resource.extension !== null &&
                <Partials.Extension
                    extension={resource.extension}
                    name='Extension'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='extension'
                />
            }
            {
                resource.modifierExtension !== undefined && resource.modifierExtension !== null &&
                <Partials.Extension
                    extension={resource.modifierExtension}
                    name='Modifier Extension'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='modifier-extension'
                />
            }
            {
                resource.identifier !== undefined && resource.identifier !== null &&
                <Partials.Identifier
                    identifier={resource.identifier}
                    name='Identifier'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='identifier'
                />
            }
            {
                resource.status &&
                <Partials.Code code={resource.status} name='Status'/>
            }
            {
                resource.manufacturedDoseForm !== undefined && resource.manufacturedDoseForm !== null &&
                <Partials.CodeableConcept
                    codeableConcept={resource.manufacturedDoseForm}
                    name='Manufactured Dose Form'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='manufactured-dose-form'
                />
            }
            {
                resource.unitOfPresentation !== undefined && resource.unitOfPresentation !== null &&
                <Partials.CodeableConcept
                    codeableConcept={resource.unitOfPresentation}
                    name='Unit Of Presentation'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='unit-of-presentation'
                />
            }
            {
                resource.manufacturer !== undefined && resource.manufacturer !== null &&
                <Partials.Reference
                    reference={resource.manufacturer}
                    name='Manufacturer'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='manufacturer'
                />
            }
            {
                resource.ingredient !== undefined && resource.ingredient !== null &&
                <Partials.CodeableConcept
                    codeableConcept={resource.ingredient}
                    name='Ingredient'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='ingredient'
                />
            }
        </>
    );
};

export default ManufacturedItemDefinition;
