// This file is auto-generated by generate_components so do not edit manually

/**
Measure
    The Measure resource provides the definition of a quality measure.
    If the element is present, it must have either a @value, an @id, or extensions
*/

import React from 'react';
import { Link } from 'react-router';
import { TMeasure } from '../../types/resources/Measure';

// Import all the partial resource
import Partials from '../../partials';
import { IdentifierSystem } from '../../utils/identifierSystem';

const Measure = ({ resource }: { resource: TMeasure }): React.ReactElement => {
    const tagUUID = resource?.meta?.tag?.find((s) => s.system === IdentifierSystem.uuid)?.code;
    const uuid = tagUUID ? tagUUID : resource.id;

    return (
        <>
            <Link title="Direct link to Resource" to={`/4_0_0/${resource.resourceType}/${uuid}`}>
                {resource.resourceType}/{uuid}
            </Link>
            {
                resource.id !== undefined && resource.id !== null &&
                <Partials.String
                    string={resource.id}
                    name='Id'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='id'
                />
            }
            {
                resource.meta !== undefined && resource.meta !== null &&
                <Partials.Meta
                    meta={resource.meta}
                    name='Meta'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='meta'
                />
            }
            {
                resource.implicitRules !== undefined && resource.implicitRules !== null &&
                <Partials.Uri
                    uri={resource.implicitRules}
                    name='Implicit Rules'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='implicit-rules'
                />
            }
            {
                resource.language &&
                <Partials.Code code={resource.language} name='Language'/>
            }
            {
                resource.text !== undefined && resource.text !== null &&
                <Partials.Narrative
                    narrative={resource.text}
                    name='Text'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='text'
                />
            }
            {
                resource.extension !== undefined && resource.extension !== null &&
                <Partials.Extension
                    extension={resource.extension}
                    name='Extension'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='extension'
                />
            }
            {
                resource.modifierExtension !== undefined && resource.modifierExtension !== null &&
                <Partials.Extension
                    extension={resource.modifierExtension}
                    name='Modifier Extension'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='modifier-extension'
                />
            }
            {
                resource.url !== undefined && resource.url !== null &&
                <Partials.Uri
                    uri={resource.url}
                    name='Url'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='url'
                />
            }
            {
                resource.identifier !== undefined && resource.identifier !== null &&
                <Partials.Identifier
                    identifier={resource.identifier}
                    name='Identifier'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='identifier'
                />
            }
            {
                resource.version !== undefined && resource.version !== null &&
                <Partials.String
                    string={resource.version}
                    name='Version'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='version'
                />
            }
            {
                resource.name !== undefined && resource.name !== null &&
                <Partials.String
                    string={resource.name}
                    name='Name'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='name'
                />
            }
            {
                resource.title !== undefined && resource.title !== null &&
                <Partials.String
                    string={resource.title}
                    name='Title'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='title'
                />
            }
            {
                resource.subtitle !== undefined && resource.subtitle !== null &&
                <Partials.String
                    string={resource.subtitle}
                    name='Subtitle'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='subtitle'
                />
            }
            {
                resource.status &&
                <Partials.Code code={resource.status} name='Status'/>
            }
            {
                resource.experimental !== undefined && resource.experimental !== null &&
                <Partials.Boolean
                    boolean={resource.experimental}
                    name='Experimental'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='experimental'
                />
            }
            {
                resource.subjectCodeableConcept !== undefined && resource.subjectCodeableConcept !== null &&
                <Partials.CodeableConcept
                    codeableConcept={resource.subjectCodeableConcept}
                    name='Subject Codeable Concept'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='subject-codeable-concept'
                />
            }
            {
                resource.subjectReference !== undefined && resource.subjectReference !== null &&
                <Partials.Reference
                    reference={resource.subjectReference}
                    name='Subject Reference'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='subject-reference'
                />
            }
            {
                resource.date !== undefined && resource.date !== null &&
                <Partials.DateTime
                    dateTime={resource.date}
                    name='Date'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='date'
                />
            }
            {
                resource.publisher !== undefined && resource.publisher !== null &&
                <Partials.String
                    string={resource.publisher}
                    name='Publisher'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='publisher'
                />
            }
            {
                resource.description !== undefined && resource.description !== null &&
                <Partials.Markdown
                    markdown={resource.description}
                    name='Description'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='description'
                />
            }
            {
                resource.jurisdiction !== undefined && resource.jurisdiction !== null &&
                <Partials.CodeableConcept
                    codeableConcept={resource.jurisdiction}
                    name='Jurisdiction'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='jurisdiction'
                />
            }
            {
                resource.purpose !== undefined && resource.purpose !== null &&
                <Partials.Markdown
                    markdown={resource.purpose}
                    name='Purpose'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='purpose'
                />
            }
            {
                resource.usage !== undefined && resource.usage !== null &&
                <Partials.String
                    string={resource.usage}
                    name='Usage'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='usage'
                />
            }
            {
                resource.copyright !== undefined && resource.copyright !== null &&
                <Partials.Markdown
                    markdown={resource.copyright}
                    name='Copyright'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='copyright'
                />
            }
            {
                resource.approvalDate !== undefined && resource.approvalDate !== null &&
                <Partials.Date
                    date={resource.approvalDate}
                    name='Approval Date'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='approval-date'
                />
            }
            {
                resource.lastReviewDate !== undefined && resource.lastReviewDate !== null &&
                <Partials.Date
                    date={resource.lastReviewDate}
                    name='Last Review Date'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='last-review-date'
                />
            }
            {
                resource.effectivePeriod !== undefined && resource.effectivePeriod !== null &&
                <Partials.Period
                    period={resource.effectivePeriod}
                    name='Effective Period'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='effective-period'
                />
            }
            {
                resource.topic !== undefined && resource.topic !== null &&
                <Partials.CodeableConcept
                    codeableConcept={resource.topic}
                    name='Topic'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='topic'
                />
            }
            {
                resource.relatedArtifact !== undefined && resource.relatedArtifact !== null &&
                <Partials.RelatedArtifact
                    relatedArtifact={resource.relatedArtifact}
                    name='Related Artifact'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='related-artifact'
                />
            }
            {
                resource.library !== undefined && resource.library !== null &&
                <Partials.Canonical
                    canonical={resource.library}
                    name='Library'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='library'
                />
            }
            {
                resource.disclaimer !== undefined && resource.disclaimer !== null &&
                <Partials.Markdown
                    markdown={resource.disclaimer}
                    name='Disclaimer'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='disclaimer'
                />
            }
            {
                resource.scoring !== undefined && resource.scoring !== null &&
                <Partials.CodeableConcept
                    codeableConcept={resource.scoring}
                    name='Scoring'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='scoring'
                />
            }
            {
                resource.compositeScoring !== undefined && resource.compositeScoring !== null &&
                <Partials.CodeableConcept
                    codeableConcept={resource.compositeScoring}
                    name='Composite Scoring'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='composite-scoring'
                />
            }
            {
                resource.type !== undefined && resource.type !== null &&
                <Partials.CodeableConcept
                    codeableConcept={resource.type}
                    name='Type'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='type'
                />
            }
            {
                resource.riskAdjustment !== undefined && resource.riskAdjustment !== null &&
                <Partials.String
                    string={resource.riskAdjustment}
                    name='Risk Adjustment'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='risk-adjustment'
                />
            }
            {
                resource.rateAggregation !== undefined && resource.rateAggregation !== null &&
                <Partials.String
                    string={resource.rateAggregation}
                    name='Rate Aggregation'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='rate-aggregation'
                />
            }
            {
                resource.rationale !== undefined && resource.rationale !== null &&
                <Partials.Markdown
                    markdown={resource.rationale}
                    name='Rationale'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='rationale'
                />
            }
            {
                resource.clinicalRecommendationStatement !== undefined && resource.clinicalRecommendationStatement !== null &&
                <Partials.Markdown
                    markdown={resource.clinicalRecommendationStatement}
                    name='Clinical Recommendation Statement'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='clinical-recommendation-statement'
                />
            }
            {
                resource.improvementNotation !== undefined && resource.improvementNotation !== null &&
                <Partials.CodeableConcept
                    codeableConcept={resource.improvementNotation}
                    name='Improvement Notation'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='improvement-notation'
                />
            }
            {
                resource.definition !== undefined && resource.definition !== null &&
                <Partials.Markdown
                    markdown={resource.definition}
                    name='Definition'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='definition'
                />
            }
            {
                resource.guidance !== undefined && resource.guidance !== null &&
                <Partials.Markdown
                    markdown={resource.guidance}
                    name='Guidance'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='guidance'
                />
            }
            {
                resource.group !== undefined && resource.group !== null &&
                <Partials.MeasureGroup
                    group={resource.group}
                    name='Group'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='group'
                    field=''
                />
            }
            {
                resource.supplementalData !== undefined && resource.supplementalData !== null &&
                <Partials.MeasureSupplementalData
                    supplementalData={resource.supplementalData}
                    name='Supplemental Data'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='supplemental-data'
                    field=''
                />
            }
        </>
    );
};

export default Measure;
