// This file is auto-generated by generate_components so do not edit manually

/**
MedicationKnowledge
    Information about a medication that is used to support knowledge.
    If the element is present, it must have either a @value, an @id, or extensions
*/

import React from 'react';
import { Link } from 'react-router';
import { TMedicationKnowledge } from '../../types/resources/MedicationKnowledge';

// Import all the partial resource
import Partials from '../../partials';
import { IdentifierSystem } from '../../utils/identifierSystem';

const MedicationKnowledge = ({ resource }: { resource: TMedicationKnowledge }): React.ReactElement => {
    const tagUUID = resource?.meta?.tag?.find((s) => s.system === IdentifierSystem.uuid)?.code;
    const uuid = tagUUID ? tagUUID : resource.id;

    return (
        <>
            <Link title="Direct link to Resource" to={`/4_0_0/${resource.resourceType}/${uuid}`}>
                {resource.resourceType}/{uuid}
            </Link>
            {
                resource.id !== undefined && resource.id !== null &&
                <Partials.String
                    string={resource.id}
                    name='Id'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='id'
                />
            }
            {
                resource.meta !== undefined && resource.meta !== null &&
                <Partials.Meta
                    meta={resource.meta}
                    name='Meta'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='meta'
                />
            }
            {
                resource.implicitRules !== undefined && resource.implicitRules !== null &&
                <Partials.Uri
                    uri={resource.implicitRules}
                    name='Implicit Rules'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='implicit-rules'
                />
            }
            {
                resource.language &&
                <Partials.Code code={resource.language} name='Language'/>
            }
            {
                resource.text !== undefined && resource.text !== null &&
                <Partials.Narrative
                    narrative={resource.text}
                    name='Text'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='text'
                />
            }
            {
                resource.extension !== undefined && resource.extension !== null &&
                <Partials.Extension
                    extension={resource.extension}
                    name='Extension'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='extension'
                />
            }
            {
                resource.modifierExtension !== undefined && resource.modifierExtension !== null &&
                <Partials.Extension
                    extension={resource.modifierExtension}
                    name='Modifier Extension'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='modifier-extension'
                />
            }
            {
                resource.code !== undefined && resource.code !== null &&
                <Partials.CodeableConcept
                    codeableConcept={resource.code}
                    name='Code'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='code'
                />
            }
            {
                resource.status &&
                <Partials.Code code={resource.status} name='Status'/>
            }
            {
                resource.manufacturer !== undefined && resource.manufacturer !== null &&
                <Partials.Reference
                    reference={resource.manufacturer}
                    name='Manufacturer'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='manufacturer'
                />
            }
            {
                resource.doseForm !== undefined && resource.doseForm !== null &&
                <Partials.CodeableConcept
                    codeableConcept={resource.doseForm}
                    name='Dose Form'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='dose-form'
                />
            }
            {
                resource.amount !== undefined && resource.amount !== null &&
                <Partials.Quantity
                    quantity={resource.amount}
                    name='Amount'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='amount'
                />
            }
            {
                resource.synonym !== undefined && resource.synonym !== null &&
                <Partials.String
                    string={resource.synonym}
                    name='Synonym'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='synonym'
                />
            }
            {
                resource.associatedMedication !== undefined && resource.associatedMedication !== null &&
                <Partials.Reference
                    reference={resource.associatedMedication}
                    name='Associated Medication'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='associated-medication'
                />
            }
            {
                resource.productType !== undefined && resource.productType !== null &&
                <Partials.CodeableConcept
                    codeableConcept={resource.productType}
                    name='Product Type'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='product-type'
                />
            }
            {
                resource.ingredient !== undefined && resource.ingredient !== null &&
                <Partials.MedicationKnowledgeIngredient
                    ingredient={resource.ingredient}
                    name='Ingredient'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='ingredient'
                    field=''
                />
            }
            {
                resource.preparationInstruction !== undefined && resource.preparationInstruction !== null &&
                <Partials.Markdown
                    markdown={resource.preparationInstruction}
                    name='Preparation Instruction'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='preparation-instruction'
                />
            }
            {
                resource.intendedRoute !== undefined && resource.intendedRoute !== null &&
                <Partials.CodeableConcept
                    codeableConcept={resource.intendedRoute}
                    name='Intended Route'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='intended-route'
                />
            }
            {
                resource.administrationGuidelines !== undefined && resource.administrationGuidelines !== null &&
                <Partials.MedicationKnowledgeAdministrationGuidelines
                    administrationGuidelines={resource.administrationGuidelines}
                    name='Administration Guidelines'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='administration-guidelines'
                    field=''
                />
            }
            {
                resource.drugCharacteristic !== undefined && resource.drugCharacteristic !== null &&
                <Partials.MedicationKnowledgeDrugCharacteristic
                    drugCharacteristic={resource.drugCharacteristic}
                    name='Drug Characteristic'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='drug-characteristic'
                    field=''
                />
            }
            {
                resource.contraindication !== undefined && resource.contraindication !== null &&
                <Partials.Reference
                    reference={resource.contraindication}
                    name='Contraindication'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='contraindication'
                />
            }
            {
                resource.regulatory !== undefined && resource.regulatory !== null &&
                <Partials.Reference
                    reference={resource.regulatory}
                    name='Regulatory'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='regulatory'
                    field='regulatoryAuthority'
                />
            }
        </>
    );
};

export default MedicationKnowledge;
