// This file is auto-generated by generate_components so do not edit manually

/**
MedicationRequest
    An order or request for both supply of the medication and the instructions for
    administration of the medication to a patient. The resource is called
    "MedicationRequest" rather than "MedicationPrescription" or "MedicationOrder"
    to generalize the use across inpatient and outpatient settings, including care
    plans, etc., and to harmonize with workflow patterns.
    If the element is present, it must have either a @value, an @id, or extensions
*/

import React from 'react';
import { Link } from 'react-router';
import { TMedicationRequest } from '../../types/resources/MedicationRequest';

// Import all the partial resource
import Partials from '../../partials';
import { IdentifierSystem } from '../../utils/identifierSystem';

const MedicationRequest = ({ resource }: { resource: TMedicationRequest }): React.ReactElement => {
    const tagUUID = resource?.meta?.tag?.find((s) => s.system === IdentifierSystem.uuid)?.code;
    const uuid = tagUUID ? tagUUID : resource.id;

    return (
        <>
            <Link title="Direct link to Resource" to={`/4_0_0/${resource.resourceType}/${uuid}`}>
                {resource.resourceType}/{uuid}
            </Link>
            {
                resource.id !== undefined && resource.id !== null &&
                <Partials.String
                    string={resource.id}
                    name='Id'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='id'
                />
            }
            {
                resource.meta !== undefined && resource.meta !== null &&
                <Partials.Meta
                    meta={resource.meta}
                    name='Meta'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='meta'
                />
            }
            {
                resource.implicitRules !== undefined && resource.implicitRules !== null &&
                <Partials.Uri
                    uri={resource.implicitRules}
                    name='Implicit Rules'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='implicit-rules'
                />
            }
            {
                resource.language &&
                <Partials.Code code={resource.language} name='Language'/>
            }
            {
                resource.text !== undefined && resource.text !== null &&
                <Partials.Narrative
                    narrative={resource.text}
                    name='Text'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='text'
                />
            }
            {
                resource.extension !== undefined && resource.extension !== null &&
                <Partials.Extension
                    extension={resource.extension}
                    name='Extension'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='extension'
                />
            }
            {
                resource.modifierExtension !== undefined && resource.modifierExtension !== null &&
                <Partials.Extension
                    extension={resource.modifierExtension}
                    name='Modifier Extension'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='modifier-extension'
                />
            }
            {
                resource.identifier !== undefined && resource.identifier !== null &&
                <Partials.Identifier
                    identifier={resource.identifier}
                    name='Identifier'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='identifier'
                />
            }
            {
                resource.status &&
                <Partials.Code code={resource.status} name='Status'/>
            }
            {
                resource.statusReason !== undefined && resource.statusReason !== null &&
                <Partials.CodeableConcept
                    codeableConcept={resource.statusReason}
                    name='Status Reason'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='status-reason'
                />
            }
            {
                resource.intent &&
                <Partials.Code code={resource.intent} name='Intent'/>
            }
            {
                resource.category !== undefined && resource.category !== null &&
                <Partials.CodeableConcept
                    codeableConcept={resource.category}
                    name='Category'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='category'
                />
            }
            {
                resource.priority &&
                <Partials.Code code={resource.priority} name='Priority'/>
            }
            {
                resource.doNotPerform !== undefined && resource.doNotPerform !== null &&
                <Partials.Boolean
                    boolean={resource.doNotPerform}
                    name='Do Not Perform'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='do-not-perform'
                />
            }
            {
                resource.reportedBoolean !== undefined && resource.reportedBoolean !== null &&
                <Partials.Boolean
                    boolean={resource.reportedBoolean}
                    name='Reported Boolean'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='reported-boolean'
                />
            }
            {
                resource.reportedReference !== undefined && resource.reportedReference !== null &&
                <Partials.Reference
                    reference={resource.reportedReference}
                    name='Reported Reference'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='reported-reference'
                />
            }
            {
                resource.medicationCodeableConcept !== undefined && resource.medicationCodeableConcept !== null &&
                <Partials.CodeableConcept
                    codeableConcept={resource.medicationCodeableConcept}
                    name='Medication Codeable Concept'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='medication-codeable-concept'
                />
            }
            {
                resource.medicationReference !== undefined && resource.medicationReference !== null &&
                <Partials.Reference
                    reference={resource.medicationReference}
                    name='Medication Reference'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='medication-reference'
                />
            }
            {
                resource.subject !== undefined && resource.subject !== null &&
                <Partials.Reference
                    reference={resource.subject}
                    name='Subject'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='subject'
                />
            }
            {
                resource.encounter !== undefined && resource.encounter !== null &&
                <Partials.Reference
                    reference={resource.encounter}
                    name='Encounter'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='encounter'
                />
            }
            {
                resource.supportingInformation !== undefined && resource.supportingInformation !== null &&
                <Partials.Reference
                    reference={resource.supportingInformation}
                    name='Supporting Information'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='supporting-information'
                />
            }
            {
                resource.authoredOn !== undefined && resource.authoredOn !== null &&
                <Partials.DateTime
                    dateTime={resource.authoredOn}
                    name='Authored On'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='authored-on'
                />
            }
            {
                resource.requester !== undefined && resource.requester !== null &&
                <Partials.Reference
                    reference={resource.requester}
                    name='Requester'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='requester'
                />
            }
            {
                resource.performer !== undefined && resource.performer !== null &&
                <Partials.Reference
                    reference={resource.performer}
                    name='Performer'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='performer'
                />
            }
            {
                resource.performerType !== undefined && resource.performerType !== null &&
                <Partials.CodeableConcept
                    codeableConcept={resource.performerType}
                    name='Performer Type'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='performer-type'
                />
            }
            {
                resource.recorder !== undefined && resource.recorder !== null &&
                <Partials.Reference
                    reference={resource.recorder}
                    name='Recorder'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='recorder'
                />
            }
            {
                resource.reasonCode !== undefined && resource.reasonCode !== null &&
                <Partials.CodeableConcept
                    codeableConcept={resource.reasonCode}
                    name='Reason Code'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='reason-code'
                />
            }
            {
                resource.reasonReference !== undefined && resource.reasonReference !== null &&
                <Partials.Reference
                    reference={resource.reasonReference}
                    name='Reason Reference'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='reason-reference'
                />
            }
            {
                resource.instantiatesCanonical !== undefined && resource.instantiatesCanonical !== null &&
                <Partials.Canonical
                    canonical={resource.instantiatesCanonical}
                    name='Instantiates Canonical'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='instantiates-canonical'
                />
            }
            {
                resource.instantiatesUri !== undefined && resource.instantiatesUri !== null &&
                <Partials.Uri
                    uri={resource.instantiatesUri}
                    name='Instantiates Uri'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='instantiates-uri'
                />
            }
            {
                resource.basedOn !== undefined && resource.basedOn !== null &&
                <Partials.Reference
                    reference={resource.basedOn}
                    name='Based On'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='based-on'
                />
            }
            {
                resource.groupIdentifier !== undefined && resource.groupIdentifier !== null &&
                <Partials.Identifier
                    identifier={resource.groupIdentifier}
                    name='Group Identifier'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='group-identifier'
                />
            }
            {
                resource.courseOfTherapyType !== undefined && resource.courseOfTherapyType !== null &&
                <Partials.CodeableConcept
                    codeableConcept={resource.courseOfTherapyType}
                    name='Course Of Therapy Type'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='course-of-therapy-type'
                />
            }
            {
                resource.insurance !== undefined && resource.insurance !== null &&
                <Partials.Reference
                    reference={resource.insurance}
                    name='Insurance'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='insurance'
                />
            }
            {
                resource.note !== undefined && resource.note !== null &&
                <Partials.Annotation
                    annotation={resource.note}
                    name='Note'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='note'
                />
            }
            {
                resource.dosageInstruction !== undefined && resource.dosageInstruction !== null &&
                <Partials.Dosage
                    dosage={resource.dosageInstruction}
                    name='Dosage Instruction'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='dosage-instruction'
                />
            }
            {
                resource.dispenseRequest !== undefined && resource.dispenseRequest !== null &&
                <Partials.MedicationRequestDispenseRequest
                    dispenseRequest={resource.dispenseRequest}
                    name='Dispense Request'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='dispense-request'
                    field=''
                />
            }
            {
                resource.substitution !== undefined && resource.substitution !== null &&
                <Partials.MedicationRequestSubstitution
                    substitution={resource.substitution}
                    name='Substitution'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='substitution'
                    field=''
                />
            }
            {
                resource.priorPrescription !== undefined && resource.priorPrescription !== null &&
                <Partials.Reference
                    reference={resource.priorPrescription}
                    name='Prior Prescription'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='prior-prescription'
                />
            }
            {
                resource.detectedIssue !== undefined && resource.detectedIssue !== null &&
                <Partials.Reference
                    reference={resource.detectedIssue}
                    name='Detected Issue'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='detected-issue'
                />
            }
            {
                resource.eventHistory !== undefined && resource.eventHistory !== null &&
                <Partials.Reference
                    reference={resource.eventHistory}
                    name='Event History'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='event-history'
                />
            }
        </>
    );
};

export default MedicationRequest;
