// This file is auto-generated by generate_components so do not edit manually

/**
MolecularSequence
    Raw data describing a biological sequence.
    If the element is present, it must have either a @value, an @id, or extensions
*/

import React from 'react';
import { Link } from 'react-router';
import { TMolecularSequence } from '../../types/resources/MolecularSequence';

// Import all the partial resource
import Partials from '../../partials';
import { IdentifierSystem } from '../../utils/identifierSystem';

const MolecularSequence = ({ resource }: { resource: TMolecularSequence }): React.ReactElement => {
    const tagUUID = resource?.meta?.tag?.find((s) => s.system === IdentifierSystem.uuid)?.code;
    const uuid = tagUUID ? tagUUID : resource.id;

    return (
        <>
            <Link title="Direct link to Resource" to={`/4_0_0/${resource.resourceType}/${uuid}`}>
                {resource.resourceType}/{uuid}
            </Link>
            {
                resource.id !== undefined && resource.id !== null &&
                <Partials.String
                    string={resource.id}
                    name='Id'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='id'
                />
            }
            {
                resource.meta !== undefined && resource.meta !== null &&
                <Partials.Meta
                    meta={resource.meta}
                    name='Meta'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='meta'
                />
            }
            {
                resource.implicitRules !== undefined && resource.implicitRules !== null &&
                <Partials.Uri
                    uri={resource.implicitRules}
                    name='Implicit Rules'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='implicit-rules'
                />
            }
            {
                resource.language &&
                <Partials.Code code={resource.language} name='Language'/>
            }
            {
                resource.text !== undefined && resource.text !== null &&
                <Partials.Narrative
                    narrative={resource.text}
                    name='Text'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='text'
                />
            }
            {
                resource.extension !== undefined && resource.extension !== null &&
                <Partials.Extension
                    extension={resource.extension}
                    name='Extension'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='extension'
                />
            }
            {
                resource.modifierExtension !== undefined && resource.modifierExtension !== null &&
                <Partials.Extension
                    extension={resource.modifierExtension}
                    name='Modifier Extension'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='modifier-extension'
                />
            }
            {
                resource.identifier !== undefined && resource.identifier !== null &&
                <Partials.Identifier
                    identifier={resource.identifier}
                    name='Identifier'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='identifier'
                />
            }
            {
                resource.type &&
                <Partials.Code code={resource.type} name='Type'/>
            }
            {
                resource.coordinateSystem !== undefined && resource.coordinateSystem !== null &&
                <Partials.Int
                    int={resource.coordinateSystem}
                    name='Coordinate System'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='coordinate-system'
                />
            }
            {
                resource.patient !== undefined && resource.patient !== null &&
                <Partials.Reference
                    reference={resource.patient}
                    name='Patient'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='patient'
                />
            }
            {
                resource.specimen !== undefined && resource.specimen !== null &&
                <Partials.Reference
                    reference={resource.specimen}
                    name='Specimen'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='specimen'
                />
            }
            {
                resource.device !== undefined && resource.device !== null &&
                <Partials.Reference
                    reference={resource.device}
                    name='Device'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='device'
                />
            }
            {
                resource.performer !== undefined && resource.performer !== null &&
                <Partials.Reference
                    reference={resource.performer}
                    name='Performer'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='performer'
                />
            }
            {
                resource.quantity !== undefined && resource.quantity !== null &&
                <Partials.Quantity
                    quantity={resource.quantity}
                    name='Quantity'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='quantity'
                />
            }
            {
                resource.referenceSeq !== undefined && resource.referenceSeq !== null &&
                <Partials.MolecularSequenceReferenceSeq
                    referenceSeq={resource.referenceSeq}
                    name='Reference Seq'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='reference-seq'
                    field=''
                />
            }
            {
                resource.variant !== undefined && resource.variant !== null &&
                <Partials.MolecularSequenceVariant
                    variant={resource.variant}
                    name='Variant'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='variant'
                    field=''
                />
            }
            {
                resource.observedSeq !== undefined && resource.observedSeq !== null &&
                <Partials.String
                    string={resource.observedSeq}
                    name='Observed Seq'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='observed-seq'
                />
            }
            {
                resource.quality !== undefined && resource.quality !== null &&
                <Partials.MolecularSequenceQuality
                    quality={resource.quality}
                    name='Quality'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='quality'
                    field=''
                />
            }
            {
                resource.readCoverage !== undefined && resource.readCoverage !== null &&
                <Partials.Int
                    int={resource.readCoverage}
                    name='Read Coverage'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='read-coverage'
                />
            }
            {
                resource.pointer !== undefined && resource.pointer !== null &&
                <Partials.Reference
                    reference={resource.pointer}
                    name='Pointer'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='pointer'
                />
            }
            {
                resource.structureVariant !== undefined && resource.structureVariant !== null &&
                <Partials.MolecularSequenceStructureVariant
                    structureVariant={resource.structureVariant}
                    name='Structure Variant'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='structure-variant'
                    field=''
                />
            }
        </>
    );
};

export default MolecularSequence;
