// This file is auto-generated by generate_components so do not edit manually

/**
Observation
    Measurements and simple assertions made about a patient, device or other
    subject.
    If the element is present, it must have either a @value, an @id, or extensions
*/

import React from 'react';
import { Link } from 'react-router';
import { TObservation } from '../../types/resources/Observation';

// Import all the partial resource
import Partials from '../../partials';
import { IdentifierSystem } from '../../utils/identifierSystem';

const Observation = ({ resource }: { resource: TObservation }): React.ReactElement => {
    const tagUUID = resource?.meta?.tag?.find((s) => s.system === IdentifierSystem.uuid)?.code;
    const uuid = tagUUID ? tagUUID : resource.id;

    return (
        <>
            <Link title="Direct link to Resource" to={`/4_0_0/${resource.resourceType}/${uuid}`}>
                {resource.resourceType}/{uuid}
            </Link>
            {
                resource.id !== undefined && resource.id !== null &&
                <Partials.String
                    string={resource.id}
                    name='Id'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='id'
                />
            }
            {
                resource.meta !== undefined && resource.meta !== null &&
                <Partials.Meta
                    meta={resource.meta}
                    name='Meta'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='meta'
                />
            }
            {
                resource.implicitRules !== undefined && resource.implicitRules !== null &&
                <Partials.Uri
                    uri={resource.implicitRules}
                    name='Implicit Rules'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='implicit-rules'
                />
            }
            {
                resource.language &&
                <Partials.Code code={resource.language} name='Language'/>
            }
            {
                resource.text !== undefined && resource.text !== null &&
                <Partials.Narrative
                    narrative={resource.text}
                    name='Text'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='text'
                />
            }
            {
                resource.extension !== undefined && resource.extension !== null &&
                <Partials.Extension
                    extension={resource.extension}
                    name='Extension'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='extension'
                />
            }
            {
                resource.modifierExtension !== undefined && resource.modifierExtension !== null &&
                <Partials.Extension
                    extension={resource.modifierExtension}
                    name='Modifier Extension'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='modifier-extension'
                />
            }
            {
                resource.identifier !== undefined && resource.identifier !== null &&
                <Partials.Identifier
                    identifier={resource.identifier}
                    name='Identifier'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='identifier'
                />
            }
            {
                resource.basedOn !== undefined && resource.basedOn !== null &&
                <Partials.Reference
                    reference={resource.basedOn}
                    name='Based On'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='based-on'
                />
            }
            {
                resource.partOf !== undefined && resource.partOf !== null &&
                <Partials.Reference
                    reference={resource.partOf}
                    name='Part Of'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='part-of'
                />
            }
            {
                resource.status &&
                <Partials.Code code={resource.status} name='Status'/>
            }
            {
                resource.category !== undefined && resource.category !== null &&
                <Partials.CodeableConcept
                    codeableConcept={resource.category}
                    name='Category'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='category'
                />
            }
            {
                resource.code !== undefined && resource.code !== null &&
                <Partials.CodeableConcept
                    codeableConcept={resource.code}
                    name='Code'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='code'
                />
            }
            {
                resource.subject !== undefined && resource.subject !== null &&
                <Partials.Reference
                    reference={resource.subject}
                    name='Subject'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='subject'
                />
            }
            {
                resource.focus !== undefined && resource.focus !== null &&
                <Partials.Reference
                    reference={resource.focus}
                    name='Focus'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='focus'
                />
            }
            {
                resource.encounter !== undefined && resource.encounter !== null &&
                <Partials.Reference
                    reference={resource.encounter}
                    name='Encounter'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='encounter'
                />
            }
            {
                resource.effectiveDateTime !== undefined && resource.effectiveDateTime !== null &&
                <Partials.DateTime
                    dateTime={resource.effectiveDateTime}
                    name='Effective Date Time'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='effective-date-time'
                />
            }
            {
                resource.effectivePeriod !== undefined && resource.effectivePeriod !== null &&
                <Partials.Period
                    period={resource.effectivePeriod}
                    name='Effective Period'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='effective-period'
                />
            }
            {
                resource.effectiveTiming !== undefined && resource.effectiveTiming !== null &&
                <Partials.Timing
                    timing={resource.effectiveTiming}
                    name='Effective Timing'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='effective-timing'
                />
            }
            {
                resource.effectiveInstant !== undefined && resource.effectiveInstant !== null &&
                <Partials.Instant
                    instant={resource.effectiveInstant}
                    name='Effective Instant'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='effective-instant'
                />
            }
            {
                resource.issued !== undefined && resource.issued !== null &&
                <Partials.Instant
                    instant={resource.issued}
                    name='Issued'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='issued'
                />
            }
            {
                resource.performer !== undefined && resource.performer !== null &&
                <Partials.Reference
                    reference={resource.performer}
                    name='Performer'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='performer'
                />
            }
            {
                resource.valueQuantity !== undefined && resource.valueQuantity !== null &&
                <Partials.Quantity
                    quantity={resource.valueQuantity}
                    name='Value Quantity'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='value-quantity'
                />
            }
            {
                resource.valueCodeableConcept !== undefined && resource.valueCodeableConcept !== null &&
                <Partials.CodeableConcept
                    codeableConcept={resource.valueCodeableConcept}
                    name='Value Codeable Concept'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='value-codeable-concept'
                />
            }
            {
                resource.valueString !== undefined && resource.valueString !== null &&
                <Partials.String
                    string={resource.valueString}
                    name='Value String'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='value-string'
                />
            }
            {
                resource.valueBoolean !== undefined && resource.valueBoolean !== null &&
                <Partials.Boolean
                    boolean={resource.valueBoolean}
                    name='Value Boolean'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='value-boolean'
                />
            }
            {
                resource.valueInteger !== undefined && resource.valueInteger !== null &&
                <Partials.Int
                    int={resource.valueInteger}
                    name='Value Integer'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='value-integer'
                />
            }
            {
                resource.valueRange !== undefined && resource.valueRange !== null &&
                <Partials.Range
                    range={resource.valueRange}
                    name='Value Range'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='value-range'
                />
            }
            {
                resource.valueRatio !== undefined && resource.valueRatio !== null &&
                <Partials.Ratio
                    ratio={resource.valueRatio}
                    name='Value Ratio'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='value-ratio'
                />
            }
            {
                resource.valueSampledData !== undefined && resource.valueSampledData !== null &&
                <Partials.SampledData
                    sampledData={resource.valueSampledData}
                    name='Value Sampled Data'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='value-sampled-data'
                />
            }
            {
                resource.valueTime !== undefined && resource.valueTime !== null &&
                <Partials.Time
                    time={resource.valueTime}
                    name='Value Time'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='value-time'
                />
            }
            {
                resource.valueDateTime !== undefined && resource.valueDateTime !== null &&
                <Partials.DateTime
                    dateTime={resource.valueDateTime}
                    name='Value Date Time'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='value-date-time'
                />
            }
            {
                resource.valuePeriod !== undefined && resource.valuePeriod !== null &&
                <Partials.Period
                    period={resource.valuePeriod}
                    name='Value Period'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='value-period'
                />
            }
            {
                resource.dataAbsentReason !== undefined && resource.dataAbsentReason !== null &&
                <Partials.CodeableConcept
                    codeableConcept={resource.dataAbsentReason}
                    name='Data Absent Reason'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='data-absent-reason'
                />
            }
            {
                resource.interpretation !== undefined && resource.interpretation !== null &&
                <Partials.CodeableConcept
                    codeableConcept={resource.interpretation}
                    name='Interpretation'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='interpretation'
                />
            }
            {
                resource.note !== undefined && resource.note !== null &&
                <Partials.Annotation
                    annotation={resource.note}
                    name='Note'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='note'
                />
            }
            {
                resource.bodySite !== undefined && resource.bodySite !== null &&
                <Partials.CodeableConcept
                    codeableConcept={resource.bodySite}
                    name='Body Site'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='body-site'
                />
            }
            {
                resource.method !== undefined && resource.method !== null &&
                <Partials.CodeableConcept
                    codeableConcept={resource.method}
                    name='Method'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='method'
                />
            }
            {
                resource.specimen !== undefined && resource.specimen !== null &&
                <Partials.Reference
                    reference={resource.specimen}
                    name='Specimen'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='specimen'
                />
            }
            {
                resource.device !== undefined && resource.device !== null &&
                <Partials.Reference
                    reference={resource.device}
                    name='Device'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='device'
                />
            }
            {
                resource.referenceRange !== undefined && resource.referenceRange !== null &&
                <Partials.ObservationReferenceRange
                    observationReferenceRange={resource.referenceRange}
                    name='Reference Range'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='reference-range'
                />
            }
            {
                resource.hasMember !== undefined && resource.hasMember !== null &&
                <Partials.Reference
                    reference={resource.hasMember}
                    name='Has Member'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='has-member'
                />
            }
            {
                resource.derivedFrom !== undefined && resource.derivedFrom !== null &&
                <Partials.Reference
                    reference={resource.derivedFrom}
                    name='Derived From'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='derived-from'
                />
            }
            {
                resource.component !== undefined && resource.component !== null &&
                <Partials.ObservationComponent
                    component={resource.component}
                    name='Component'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='component'
                    field=''
                />
            }
        </>
    );
};

export default Observation;
