// This file is auto-generated by generate_components so do not edit manually

/**
OperationDefinition
    A formal computable definition of an operation (on the RESTful interface) or a
    named query (using the search interaction).
    If the element is present, it must have either a @value, an @id, or extensions
*/

import React from 'react';
import { Link } from 'react-router';
import { TOperationDefinition } from '../../types/resources/OperationDefinition';

// Import all the partial resource
import Partials from '../../partials';
import { IdentifierSystem } from '../../utils/identifierSystem';

const OperationDefinition = ({ resource }: { resource: TOperationDefinition }): React.ReactElement => {
    const tagUUID = resource?.meta?.tag?.find((s) => s.system === IdentifierSystem.uuid)?.code;
    const uuid = tagUUID ? tagUUID : resource.id;

    return (
        <>
            <Link title="Direct link to Resource" to={`/4_0_0/${resource.resourceType}/${uuid}`}>
                {resource.resourceType}/{uuid}
            </Link>
            {
                resource.id !== undefined && resource.id !== null &&
                <Partials.String
                    string={resource.id}
                    name='Id'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='id'
                />
            }
            {
                resource.meta !== undefined && resource.meta !== null &&
                <Partials.Meta
                    meta={resource.meta}
                    name='Meta'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='meta'
                />
            }
            {
                resource.implicitRules !== undefined && resource.implicitRules !== null &&
                <Partials.Uri
                    uri={resource.implicitRules}
                    name='Implicit Rules'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='implicit-rules'
                />
            }
            {
                resource.language &&
                <Partials.Code code={resource.language} name='Language'/>
            }
            {
                resource.text !== undefined && resource.text !== null &&
                <Partials.Narrative
                    narrative={resource.text}
                    name='Text'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='text'
                />
            }
            {
                resource.extension !== undefined && resource.extension !== null &&
                <Partials.Extension
                    extension={resource.extension}
                    name='Extension'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='extension'
                />
            }
            {
                resource.modifierExtension !== undefined && resource.modifierExtension !== null &&
                <Partials.Extension
                    extension={resource.modifierExtension}
                    name='Modifier Extension'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='modifier-extension'
                />
            }
            {
                resource.url !== undefined && resource.url !== null &&
                <Partials.Uri
                    uri={resource.url}
                    name='Url'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='url'
                />
            }
            {
                resource.version !== undefined && resource.version !== null &&
                <Partials.String
                    string={resource.version}
                    name='Version'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='version'
                />
            }
            {
                resource.name !== undefined && resource.name !== null &&
                <Partials.String
                    string={resource.name}
                    name='Name'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='name'
                />
            }
            {
                resource.title !== undefined && resource.title !== null &&
                <Partials.String
                    string={resource.title}
                    name='Title'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='title'
                />
            }
            {
                resource.status &&
                <Partials.Code code={resource.status} name='Status'/>
            }
            {
                resource.kind &&
                <Partials.Code code={resource.kind} name='Kind'/>
            }
            {
                resource.experimental !== undefined && resource.experimental !== null &&
                <Partials.Boolean
                    boolean={resource.experimental}
                    name='Experimental'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='experimental'
                />
            }
            {
                resource.date !== undefined && resource.date !== null &&
                <Partials.DateTime
                    dateTime={resource.date}
                    name='Date'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='date'
                />
            }
            {
                resource.publisher !== undefined && resource.publisher !== null &&
                <Partials.String
                    string={resource.publisher}
                    name='Publisher'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='publisher'
                />
            }
            {
                resource.description !== undefined && resource.description !== null &&
                <Partials.Markdown
                    markdown={resource.description}
                    name='Description'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='description'
                />
            }
            {
                resource.jurisdiction !== undefined && resource.jurisdiction !== null &&
                <Partials.CodeableConcept
                    codeableConcept={resource.jurisdiction}
                    name='Jurisdiction'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='jurisdiction'
                />
            }
            {
                resource.purpose !== undefined && resource.purpose !== null &&
                <Partials.Markdown
                    markdown={resource.purpose}
                    name='Purpose'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='purpose'
                />
            }
            {
                resource.affectsState !== undefined && resource.affectsState !== null &&
                <Partials.Boolean
                    boolean={resource.affectsState}
                    name='Affects State'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='affects-state'
                />
            }
            {
                resource.code &&
                <Partials.Code code={resource.code} name='Code'/>
            }
            {
                resource.comment !== undefined && resource.comment !== null &&
                <Partials.Markdown
                    markdown={resource.comment}
                    name='Comment'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='comment'
                />
            }
            {
                resource.base !== undefined && resource.base !== null &&
                <Partials.Canonical
                    canonical={resource.base}
                    name='Base'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='base'
                />
            }
            {
                resource.resource &&
                <Partials.Code code={resource.resource} name='Resource'/>
            }
            {
                resource.system !== undefined && resource.system !== null &&
                <Partials.Boolean
                    boolean={resource.system}
                    name='System'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='system'
                />
            }
            {
                resource.type !== undefined && resource.type !== null &&
                <Partials.Boolean
                    boolean={resource.type}
                    name='Type'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='type'
                />
            }
            {
                resource.instance !== undefined && resource.instance !== null &&
                <Partials.Boolean
                    boolean={resource.instance}
                    name='Instance'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='instance'
                />
            }
            {
                resource.inputProfile !== undefined && resource.inputProfile !== null &&
                <Partials.Canonical
                    canonical={resource.inputProfile}
                    name='Input Profile'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='input-profile'
                />
            }
            {
                resource.outputProfile !== undefined && resource.outputProfile !== null &&
                <Partials.Canonical
                    canonical={resource.outputProfile}
                    name='Output Profile'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='output-profile'
                />
            }
            {
                resource.parameter !== undefined && resource.parameter !== null &&
                <Partials.OperationDefinitionParameter
                    parameter={resource.parameter}
                    name='Parameter'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='parameter'
                    field=''
                />
            }
        </>
    );
};

export default OperationDefinition;
