// This file is auto-generated by generate_components so do not edit manually

/**
OperationOutcome
    A collection of error, warning, or information messages that result from a
    system action.
    If the element is present, it must have either a @value, an @id, or extensions
*/

import React from 'react';
import { Link } from 'react-router';
import { TOperationOutcome } from '../../types/resources/OperationOutcome';

// Import all the partial resource
import Partials from '../../partials';
import { IdentifierSystem } from '../../utils/identifierSystem';

const OperationOutcome = ({ resource }: { resource: TOperationOutcome }): React.ReactElement => {
    const tagUUID = resource?.meta?.tag?.find((s) => s.system === IdentifierSystem.uuid)?.code;
    const uuid = tagUUID ? tagUUID : resource.id;

    return (
        <>
            <Link title="Direct link to Resource" to={`/4_0_0/${resource.resourceType}/${uuid}`}>
                {resource.resourceType}/{uuid}
            </Link>
            {
                resource.id !== undefined && resource.id !== null &&
                <Partials.String
                    string={resource.id}
                    name='Id'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='id'
                />
            }
            {
                resource.meta !== undefined && resource.meta !== null &&
                <Partials.Meta
                    meta={resource.meta}
                    name='Meta'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='meta'
                />
            }
            {
                resource.implicitRules !== undefined && resource.implicitRules !== null &&
                <Partials.Uri
                    uri={resource.implicitRules}
                    name='Implicit Rules'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='implicit-rules'
                />
            }
            {
                resource.language &&
                <Partials.Code code={resource.language} name='Language'/>
            }
            {
                resource.text !== undefined && resource.text !== null &&
                <Partials.Narrative
                    narrative={resource.text}
                    name='Text'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='text'
                />
            }
            {
                resource.extension !== undefined && resource.extension !== null &&
                <Partials.Extension
                    extension={resource.extension}
                    name='Extension'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='extension'
                />
            }
            {
                resource.modifierExtension !== undefined && resource.modifierExtension !== null &&
                <Partials.Extension
                    extension={resource.modifierExtension}
                    name='Modifier Extension'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='modifier-extension'
                />
            }
            {
                resource.issue !== undefined && resource.issue !== null &&
                <Partials.OperationOutcomeIssue
                    operationOutcomeIssue={resource.issue}
                    name='Issue'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='issue'
                />
            }
        </>
    );
};

export default OperationOutcome;
