// This file is auto-generated by generate_components so do not edit manually

/**
PackagedProductDefinition
    A medically related item or items, in a container or package.
    If the element is present, it must have either a @value, an @id, or extensions
*/

import React from 'react';
import { Link } from 'react-router';
import { TPackagedProductDefinition } from '../../types/resources/PackagedProductDefinition';

// Import all the partial resource
import Partials from '../../partials';
import { IdentifierSystem } from '../../utils/identifierSystem';

const PackagedProductDefinition = ({ resource }: { resource: TPackagedProductDefinition }): React.ReactElement => {
    const tagUUID = resource?.meta?.tag?.find((s) => s.system === IdentifierSystem.uuid)?.code;
    const uuid = tagUUID ? tagUUID : resource.id;

    return (
        <>
            <Link title="Direct link to Resource" to={`/4_0_0/${resource.resourceType}/${uuid}`}>
                {resource.resourceType}/{uuid}
            </Link>
            {
                resource.id !== undefined && resource.id !== null &&
                <Partials.String
                    string={resource.id}
                    name='Id'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='id'
                />
            }
            {
                resource.meta !== undefined && resource.meta !== null &&
                <Partials.Meta
                    meta={resource.meta}
                    name='Meta'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='meta'
                />
            }
            {
                resource.implicitRules !== undefined && resource.implicitRules !== null &&
                <Partials.Uri
                    uri={resource.implicitRules}
                    name='Implicit Rules'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='implicit-rules'
                />
            }
            {
                resource.language &&
                <Partials.Code code={resource.language} name='Language'/>
            }
            {
                resource.text !== undefined && resource.text !== null &&
                <Partials.Narrative
                    narrative={resource.text}
                    name='Text'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='text'
                />
            }
            {
                resource.extension !== undefined && resource.extension !== null &&
                <Partials.Extension
                    extension={resource.extension}
                    name='Extension'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='extension'
                />
            }
            {
                resource.modifierExtension !== undefined && resource.modifierExtension !== null &&
                <Partials.Extension
                    extension={resource.modifierExtension}
                    name='Modifier Extension'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='modifier-extension'
                />
            }
            {
                resource.identifier !== undefined && resource.identifier !== null &&
                <Partials.Identifier
                    identifier={resource.identifier}
                    name='Identifier'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='identifier'
                />
            }
            {
                resource.name !== undefined && resource.name !== null &&
                <Partials.String
                    string={resource.name}
                    name='Name'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='name'
                />
            }
            {
                resource.type !== undefined && resource.type !== null &&
                <Partials.CodeableConcept
                    codeableConcept={resource.type}
                    name='Type'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='type'
                />
            }
            {
                resource.packageFor !== undefined && resource.packageFor !== null &&
                <Partials.Reference
                    reference={resource.packageFor}
                    name='Package For'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='package-for'
                />
            }
            {
                resource.status !== undefined && resource.status !== null &&
                <Partials.CodeableConcept
                    codeableConcept={resource.status}
                    name='Status'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='status'
                />
            }
            {
                resource.statusDate !== undefined && resource.statusDate !== null &&
                <Partials.DateTime
                    dateTime={resource.statusDate}
                    name='Status Date'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='status-date'
                />
            }
            {
                resource.containedItemQuantity !== undefined && resource.containedItemQuantity !== null &&
                <Partials.Quantity
                    quantity={resource.containedItemQuantity}
                    name='Contained Item Quantity'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='contained-item-quantity'
                />
            }
            {
                resource.description !== undefined && resource.description !== null &&
                <Partials.Markdown
                    markdown={resource.description}
                    name='Description'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='description'
                />
            }
            {
                resource.marketingStatus !== undefined && resource.marketingStatus !== null &&
                <Partials.MarketingStatus
                    marketingStatus={resource.marketingStatus}
                    name='Marketing Status'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='marketing-status'
                />
            }
            {
                resource.characteristic !== undefined && resource.characteristic !== null &&
                <Partials.CodeableConcept
                    codeableConcept={resource.characteristic}
                    name='Characteristic'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='characteristic'
                />
            }
            {
                resource.copackagedIndicator !== undefined && resource.copackagedIndicator !== null &&
                <Partials.Boolean
                    boolean={resource.copackagedIndicator}
                    name='Copackaged Indicator'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='copackaged-indicator'
                />
            }
            {
                resource.manufacturer !== undefined && resource.manufacturer !== null &&
                <Partials.Reference
                    reference={resource.manufacturer}
                    name='Manufacturer'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='manufacturer'
                />
            }
            {
                resource.package !== undefined && resource.package !== null &&
                <Partials.PackagedProductDefinitionPackage
                    package={resource.package}
                    name='Package'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='package'
                    field=''
                />
            }
        </>
    );
};

export default PackagedProductDefinition;
