// This file is auto-generated by generate_components so do not edit manually

/**
PaymentReconciliation
    This resource provides the details including amount of a payment and allocates
    the payment items being paid.
    If the element is present, it must have either a @value, an @id, or extensions
*/

import React from 'react';
import { Link } from 'react-router';
import { TPaymentReconciliation } from '../../types/resources/PaymentReconciliation';

// Import all the partial resource
import Partials from '../../partials';
import { IdentifierSystem } from '../../utils/identifierSystem';

const PaymentReconciliation = ({ resource }: { resource: TPaymentReconciliation }): React.ReactElement => {
    const tagUUID = resource?.meta?.tag?.find((s) => s.system === IdentifierSystem.uuid)?.code;
    const uuid = tagUUID ? tagUUID : resource.id;

    return (
        <>
            <Link title="Direct link to Resource" to={`/4_0_0/${resource.resourceType}/${uuid}`}>
                {resource.resourceType}/{uuid}
            </Link>
            {
                resource.id !== undefined && resource.id !== null &&
                <Partials.String
                    string={resource.id}
                    name='Id'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='id'
                />
            }
            {
                resource.meta !== undefined && resource.meta !== null &&
                <Partials.Meta
                    meta={resource.meta}
                    name='Meta'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='meta'
                />
            }
            {
                resource.implicitRules !== undefined && resource.implicitRules !== null &&
                <Partials.Uri
                    uri={resource.implicitRules}
                    name='Implicit Rules'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='implicit-rules'
                />
            }
            {
                resource.language &&
                <Partials.Code code={resource.language} name='Language'/>
            }
            {
                resource.text !== undefined && resource.text !== null &&
                <Partials.Narrative
                    narrative={resource.text}
                    name='Text'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='text'
                />
            }
            {
                resource.extension !== undefined && resource.extension !== null &&
                <Partials.Extension
                    extension={resource.extension}
                    name='Extension'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='extension'
                />
            }
            {
                resource.modifierExtension !== undefined && resource.modifierExtension !== null &&
                <Partials.Extension
                    extension={resource.modifierExtension}
                    name='Modifier Extension'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='modifier-extension'
                />
            }
            {
                resource.identifier !== undefined && resource.identifier !== null &&
                <Partials.Identifier
                    identifier={resource.identifier}
                    name='Identifier'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='identifier'
                />
            }
            {
                resource.status &&
                <Partials.Code code={resource.status} name='Status'/>
            }
            {
                resource.period !== undefined && resource.period !== null &&
                <Partials.Period
                    period={resource.period}
                    name='Period'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='period'
                />
            }
            {
                resource.created !== undefined && resource.created !== null &&
                <Partials.DateTime
                    dateTime={resource.created}
                    name='Created'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='created'
                />
            }
            {
                resource.paymentIssuer !== undefined && resource.paymentIssuer !== null &&
                <Partials.Reference
                    reference={resource.paymentIssuer}
                    name='Payment Issuer'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='payment-issuer'
                />
            }
            {
                resource.request !== undefined && resource.request !== null &&
                <Partials.Reference
                    reference={resource.request}
                    name='Request'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='request'
                />
            }
            {
                resource.requestor !== undefined && resource.requestor !== null &&
                <Partials.Reference
                    reference={resource.requestor}
                    name='Requestor'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='requestor'
                />
            }
            {
                resource.outcome &&
                <Partials.Code code={resource.outcome} name='Outcome'/>
            }
            {
                resource.disposition !== undefined && resource.disposition !== null &&
                <Partials.String
                    string={resource.disposition}
                    name='Disposition'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='disposition'
                />
            }
            {
                resource.paymentDate !== undefined && resource.paymentDate !== null &&
                <Partials.Date
                    date={resource.paymentDate}
                    name='Payment Date'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='payment-date'
                />
            }
            {
                resource.paymentAmount !== undefined && resource.paymentAmount !== null &&
                <Partials.Money
                    money={resource.paymentAmount}
                    name='Payment Amount'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='payment-amount'
                />
            }
            {
                resource.paymentIdentifier !== undefined && resource.paymentIdentifier !== null &&
                <Partials.Identifier
                    identifier={resource.paymentIdentifier}
                    name='Payment Identifier'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='payment-identifier'
                />
            }
            {
                resource.detail !== undefined && resource.detail !== null &&
                <Partials.PaymentReconciliationDetail
                    detail={resource.detail}
                    name='Detail'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='detail'
                    field=''
                />
            }
            {
                resource.formCode !== undefined && resource.formCode !== null &&
                <Partials.CodeableConcept
                    codeableConcept={resource.formCode}
                    name='Form Code'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='form-code'
                />
            }
            {
                resource.processNote !== undefined && resource.processNote !== null &&
                <Partials.PaymentReconciliationProcessNote
                    processNote={resource.processNote}
                    name='Process Note'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='process-note'
                    field=''
                />
            }
        </>
    );
};

export default PaymentReconciliation;
