// This file is auto-generated by generate_components so do not edit manually

/**
PaymentNotice
    This resource provides the status of the payment for goods and services
    rendered, and the request and response resource references.
    If the element is present, it must have either a @value, an @id, or extensions
*/

import React from 'react';
import { Link } from 'react-router';
import { TPaymentNotice } from '../../types/resources/PaymentNotice';

// Import all the partial resource
import Partials from '../../partials';
import { IdentifierSystem } from '../../utils/identifierSystem';

const PaymentNotice = ({ resource }: { resource: TPaymentNotice }): React.ReactElement => {
    const tagUUID = resource?.meta?.tag?.find((s) => s.system === IdentifierSystem.uuid)?.code;
    const uuid = tagUUID ? tagUUID : resource.id;

    return (
        <>
            <Link title="Direct link to Resource" to={`/4_0_0/${resource.resourceType}/${uuid}`}>
                {resource.resourceType}/{uuid}
            </Link>
            {
                resource.id !== undefined && resource.id !== null &&
                <Partials.String
                    string={resource.id}
                    name='Id'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='id'
                />
            }
            {
                resource.meta !== undefined && resource.meta !== null &&
                <Partials.Meta
                    meta={resource.meta}
                    name='Meta'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='meta'
                />
            }
            {
                resource.implicitRules !== undefined && resource.implicitRules !== null &&
                <Partials.Uri
                    uri={resource.implicitRules}
                    name='Implicit Rules'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='implicit-rules'
                />
            }
            {
                resource.language &&
                <Partials.Code code={resource.language} name='Language'/>
            }
            {
                resource.text !== undefined && resource.text !== null &&
                <Partials.Narrative
                    narrative={resource.text}
                    name='Text'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='text'
                />
            }
            {
                resource.extension !== undefined && resource.extension !== null &&
                <Partials.Extension
                    extension={resource.extension}
                    name='Extension'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='extension'
                />
            }
            {
                resource.modifierExtension !== undefined && resource.modifierExtension !== null &&
                <Partials.Extension
                    extension={resource.modifierExtension}
                    name='Modifier Extension'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='modifier-extension'
                />
            }
            {
                resource.identifier !== undefined && resource.identifier !== null &&
                <Partials.Identifier
                    identifier={resource.identifier}
                    name='Identifier'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='identifier'
                />
            }
            {
                resource.status &&
                <Partials.Code code={resource.status} name='Status'/>
            }
            {
                resource.request !== undefined && resource.request !== null &&
                <Partials.Reference
                    reference={resource.request}
                    name='Request'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='request'
                />
            }
            {
                resource.response !== undefined && resource.response !== null &&
                <Partials.Reference
                    reference={resource.response}
                    name='Response'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='response'
                />
            }
            {
                resource.created !== undefined && resource.created !== null &&
                <Partials.DateTime
                    dateTime={resource.created}
                    name='Created'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='created'
                />
            }
            {
                resource.provider !== undefined && resource.provider !== null &&
                <Partials.Reference
                    reference={resource.provider}
                    name='Provider'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='provider'
                />
            }
            {
                resource.payment !== undefined && resource.payment !== null &&
                <Partials.Reference
                    reference={resource.payment}
                    name='Payment'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='payment'
                />
            }
            {
                resource.paymentDate !== undefined && resource.paymentDate !== null &&
                <Partials.Date
                    date={resource.paymentDate}
                    name='Payment Date'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='payment-date'
                />
            }
            {
                resource.payee !== undefined && resource.payee !== null &&
                <Partials.Reference
                    reference={resource.payee}
                    name='Payee'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='payee'
                />
            }
            {
                resource.recipient !== undefined && resource.recipient !== null &&
                <Partials.Reference
                    reference={resource.recipient}
                    name='Recipient'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='recipient'
                />
            }
            {
                resource.amount !== undefined && resource.amount !== null &&
                <Partials.Money
                    money={resource.amount}
                    name='Amount'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='amount'
                />
            }
            {
                resource.paymentStatus !== undefined && resource.paymentStatus !== null &&
                <Partials.CodeableConcept
                    codeableConcept={resource.paymentStatus}
                    name='Payment Status'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='payment-status'
                />
            }
        </>
    );
};

export default PaymentNotice;
