// This file is auto-generated by generate_components so do not edit manually

/**
ResearchDefinition
    The ResearchDefinition resource describes the conditional state (population
    and any exposures being compared within the population) and outcome (if
    specified) that the knowledge (evidence, assertion, recommendation) is about.
    If the element is present, it must have either a @value, an @id, or extensions
*/

import React from 'react';
import { Link } from 'react-router';
import { TResearchDefinition } from '../../types/resources/ResearchDefinition';

// Import all the partial resource
import Partials from '../../partials';
import { IdentifierSystem } from '../../utils/identifierSystem';

const ResearchDefinition = ({ resource }: { resource: TResearchDefinition }): React.ReactElement => {
    const tagUUID = resource?.meta?.tag?.find((s) => s.system === IdentifierSystem.uuid)?.code;
    const uuid = tagUUID ? tagUUID : resource.id;

    return (
        <>
            <Link title="Direct link to Resource" to={`/4_0_0/${resource.resourceType}/${uuid}`}>
                {resource.resourceType}/{uuid}
            </Link>
            {
                resource.id !== undefined && resource.id !== null &&
                <Partials.String
                    string={resource.id}
                    name='Id'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='id'
                />
            }
            {
                resource.meta !== undefined && resource.meta !== null &&
                <Partials.Meta
                    meta={resource.meta}
                    name='Meta'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='meta'
                />
            }
            {
                resource.implicitRules !== undefined && resource.implicitRules !== null &&
                <Partials.Uri
                    uri={resource.implicitRules}
                    name='Implicit Rules'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='implicit-rules'
                />
            }
            {
                resource.language &&
                <Partials.Code code={resource.language} name='Language'/>
            }
            {
                resource.text !== undefined && resource.text !== null &&
                <Partials.Narrative
                    narrative={resource.text}
                    name='Text'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='text'
                />
            }
            {
                resource.extension !== undefined && resource.extension !== null &&
                <Partials.Extension
                    extension={resource.extension}
                    name='Extension'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='extension'
                />
            }
            {
                resource.modifierExtension !== undefined && resource.modifierExtension !== null &&
                <Partials.Extension
                    extension={resource.modifierExtension}
                    name='Modifier Extension'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='modifier-extension'
                />
            }
            {
                resource.url !== undefined && resource.url !== null &&
                <Partials.Uri
                    uri={resource.url}
                    name='Url'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='url'
                />
            }
            {
                resource.identifier !== undefined && resource.identifier !== null &&
                <Partials.Identifier
                    identifier={resource.identifier}
                    name='Identifier'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='identifier'
                />
            }
            {
                resource.version !== undefined && resource.version !== null &&
                <Partials.String
                    string={resource.version}
                    name='Version'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='version'
                />
            }
            {
                resource.name !== undefined && resource.name !== null &&
                <Partials.String
                    string={resource.name}
                    name='Name'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='name'
                />
            }
            {
                resource.title !== undefined && resource.title !== null &&
                <Partials.String
                    string={resource.title}
                    name='Title'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='title'
                />
            }
            {
                resource.shortTitle !== undefined && resource.shortTitle !== null &&
                <Partials.String
                    string={resource.shortTitle}
                    name='Short Title'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='short-title'
                />
            }
            {
                resource.subtitle !== undefined && resource.subtitle !== null &&
                <Partials.String
                    string={resource.subtitle}
                    name='Subtitle'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='subtitle'
                />
            }
            {
                resource.status &&
                <Partials.Code code={resource.status} name='Status'/>
            }
            {
                resource.experimental !== undefined && resource.experimental !== null &&
                <Partials.Boolean
                    boolean={resource.experimental}
                    name='Experimental'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='experimental'
                />
            }
            {
                resource.subjectCodeableConcept !== undefined && resource.subjectCodeableConcept !== null &&
                <Partials.CodeableConcept
                    codeableConcept={resource.subjectCodeableConcept}
                    name='Subject Codeable Concept'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='subject-codeable-concept'
                />
            }
            {
                resource.subjectReference !== undefined && resource.subjectReference !== null &&
                <Partials.Reference
                    reference={resource.subjectReference}
                    name='Subject Reference'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='subject-reference'
                />
            }
            {
                resource.date !== undefined && resource.date !== null &&
                <Partials.DateTime
                    dateTime={resource.date}
                    name='Date'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='date'
                />
            }
            {
                resource.publisher !== undefined && resource.publisher !== null &&
                <Partials.String
                    string={resource.publisher}
                    name='Publisher'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='publisher'
                />
            }
            {
                resource.description !== undefined && resource.description !== null &&
                <Partials.Markdown
                    markdown={resource.description}
                    name='Description'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='description'
                />
            }
            {
                resource.comment !== undefined && resource.comment !== null &&
                <Partials.String
                    string={resource.comment}
                    name='Comment'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='comment'
                />
            }
            {
                resource.jurisdiction !== undefined && resource.jurisdiction !== null &&
                <Partials.CodeableConcept
                    codeableConcept={resource.jurisdiction}
                    name='Jurisdiction'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='jurisdiction'
                />
            }
            {
                resource.purpose !== undefined && resource.purpose !== null &&
                <Partials.Markdown
                    markdown={resource.purpose}
                    name='Purpose'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='purpose'
                />
            }
            {
                resource.usage !== undefined && resource.usage !== null &&
                <Partials.String
                    string={resource.usage}
                    name='Usage'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='usage'
                />
            }
            {
                resource.copyright !== undefined && resource.copyright !== null &&
                <Partials.Markdown
                    markdown={resource.copyright}
                    name='Copyright'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='copyright'
                />
            }
            {
                resource.approvalDate !== undefined && resource.approvalDate !== null &&
                <Partials.Date
                    date={resource.approvalDate}
                    name='Approval Date'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='approval-date'
                />
            }
            {
                resource.lastReviewDate !== undefined && resource.lastReviewDate !== null &&
                <Partials.Date
                    date={resource.lastReviewDate}
                    name='Last Review Date'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='last-review-date'
                />
            }
            {
                resource.effectivePeriod !== undefined && resource.effectivePeriod !== null &&
                <Partials.Period
                    period={resource.effectivePeriod}
                    name='Effective Period'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='effective-period'
                />
            }
            {
                resource.topic !== undefined && resource.topic !== null &&
                <Partials.CodeableConcept
                    codeableConcept={resource.topic}
                    name='Topic'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='topic'
                />
            }
            {
                resource.relatedArtifact !== undefined && resource.relatedArtifact !== null &&
                <Partials.RelatedArtifact
                    relatedArtifact={resource.relatedArtifact}
                    name='Related Artifact'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='related-artifact'
                />
            }
            {
                resource.library !== undefined && resource.library !== null &&
                <Partials.Canonical
                    canonical={resource.library}
                    name='Library'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='library'
                />
            }
            {
                resource.population !== undefined && resource.population !== null &&
                <Partials.Reference
                    reference={resource.population}
                    name='Population'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='population'
                />
            }
            {
                resource.exposure !== undefined && resource.exposure !== null &&
                <Partials.Reference
                    reference={resource.exposure}
                    name='Exposure'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='exposure'
                />
            }
            {
                resource.exposureAlternative !== undefined && resource.exposureAlternative !== null &&
                <Partials.Reference
                    reference={resource.exposureAlternative}
                    name='Exposure Alternative'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='exposure-alternative'
                />
            }
            {
                resource.outcome !== undefined && resource.outcome !== null &&
                <Partials.Reference
                    reference={resource.outcome}
                    name='Outcome'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='outcome'
                />
            }
        </>
    );
};

export default ResearchDefinition;
