// This file is auto-generated by generate_components so do not edit manually

/**
SearchParameter
    A search parameter that defines a named search item that can be used to
    search/filter on a resource.
    If the element is present, it must have either a @value, an @id, or extensions
*/

import React from 'react';
import { Link } from 'react-router';
import { TSearchParameter } from '../../types/resources/SearchParameter';

// Import all the partial resource
import Partials from '../../partials';
import { IdentifierSystem } from '../../utils/identifierSystem';

const SearchParameter = ({ resource }: { resource: TSearchParameter }): React.ReactElement => {
    const tagUUID = resource?.meta?.tag?.find((s) => s.system === IdentifierSystem.uuid)?.code;
    const uuid = tagUUID ? tagUUID : resource.id;

    return (
        <>
            <Link title="Direct link to Resource" to={`/4_0_0/${resource.resourceType}/${uuid}`}>
                {resource.resourceType}/{uuid}
            </Link>
            {
                resource.id !== undefined && resource.id !== null &&
                <Partials.String
                    string={resource.id}
                    name='Id'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='id'
                />
            }
            {
                resource.meta !== undefined && resource.meta !== null &&
                <Partials.Meta
                    meta={resource.meta}
                    name='Meta'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='meta'
                />
            }
            {
                resource.implicitRules !== undefined && resource.implicitRules !== null &&
                <Partials.Uri
                    uri={resource.implicitRules}
                    name='Implicit Rules'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='implicit-rules'
                />
            }
            {
                resource.language &&
                <Partials.Code code={resource.language} name='Language'/>
            }
            {
                resource.text !== undefined && resource.text !== null &&
                <Partials.Narrative
                    narrative={resource.text}
                    name='Text'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='text'
                />
            }
            {
                resource.extension !== undefined && resource.extension !== null &&
                <Partials.Extension
                    extension={resource.extension}
                    name='Extension'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='extension'
                />
            }
            {
                resource.modifierExtension !== undefined && resource.modifierExtension !== null &&
                <Partials.Extension
                    extension={resource.modifierExtension}
                    name='Modifier Extension'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='modifier-extension'
                />
            }
            {
                resource.url !== undefined && resource.url !== null &&
                <Partials.Uri
                    uri={resource.url}
                    name='Url'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='url'
                />
            }
            {
                resource.version !== undefined && resource.version !== null &&
                <Partials.String
                    string={resource.version}
                    name='Version'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='version'
                />
            }
            {
                resource.name !== undefined && resource.name !== null &&
                <Partials.String
                    string={resource.name}
                    name='Name'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='name'
                />
            }
            {
                resource.derivedFrom !== undefined && resource.derivedFrom !== null &&
                <Partials.Canonical
                    canonical={resource.derivedFrom}
                    name='Derived From'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='derived-from'
                />
            }
            {
                resource.status &&
                <Partials.Code code={resource.status} name='Status'/>
            }
            {
                resource.experimental !== undefined && resource.experimental !== null &&
                <Partials.Boolean
                    boolean={resource.experimental}
                    name='Experimental'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='experimental'
                />
            }
            {
                resource.date !== undefined && resource.date !== null &&
                <Partials.DateTime
                    dateTime={resource.date}
                    name='Date'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='date'
                />
            }
            {
                resource.publisher !== undefined && resource.publisher !== null &&
                <Partials.String
                    string={resource.publisher}
                    name='Publisher'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='publisher'
                />
            }
            {
                resource.description !== undefined && resource.description !== null &&
                <Partials.Markdown
                    markdown={resource.description}
                    name='Description'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='description'
                />
            }
            {
                resource.jurisdiction !== undefined && resource.jurisdiction !== null &&
                <Partials.CodeableConcept
                    codeableConcept={resource.jurisdiction}
                    name='Jurisdiction'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='jurisdiction'
                />
            }
            {
                resource.purpose !== undefined && resource.purpose !== null &&
                <Partials.Markdown
                    markdown={resource.purpose}
                    name='Purpose'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='purpose'
                />
            }
            {
                resource.code &&
                <Partials.Code code={resource.code} name='Code'/>
            }
            {
                resource.base &&
                <Partials.Code code={resource.base} name='Base'/>
            }
            {
                resource.type &&
                <Partials.Code code={resource.type} name='Type'/>
            }
            {
                resource.expression !== undefined && resource.expression !== null &&
                <Partials.String
                    string={resource.expression}
                    name='Expression'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='expression'
                />
            }
            {
                resource.xpath !== undefined && resource.xpath !== null &&
                <Partials.String
                    string={resource.xpath}
                    name='Xpath'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='xpath'
                />
            }
            {
                resource.xpathUsage &&
                <Partials.Code code={resource.xpathUsage} name='Xpath Usage'/>
            }
            {
                resource.target &&
                <Partials.Code code={resource.target} name='Target'/>
            }
            {
                resource.multipleOr !== undefined && resource.multipleOr !== null &&
                <Partials.Boolean
                    boolean={resource.multipleOr}
                    name='Multiple Or'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='multiple-or'
                />
            }
            {
                resource.multipleAnd !== undefined && resource.multipleAnd !== null &&
                <Partials.Boolean
                    boolean={resource.multipleAnd}
                    name='Multiple And'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='multiple-and'
                />
            }
            {
                resource.comparator &&
                <Partials.Code code={resource.comparator} name='Comparator'/>
            }
            {
                resource.modifier &&
                <Partials.Code code={resource.modifier} name='Modifier'/>
            }
            {
                resource.chain !== undefined && resource.chain !== null &&
                <Partials.String
                    string={resource.chain}
                    name='Chain'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='chain'
                />
            }
            {
                resource.component !== undefined && resource.component !== null &&
                <Partials.SearchParameterComponent
                    component={resource.component}
                    name='Component'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='component'
                    field=''
                />
            }
        </>
    );
};

export default SearchParameter;
