// This file is auto-generated by generate_components so do not edit manually

/**
Slot
    A slot of time on a schedule that may be available for booking appointments.
    If the element is present, it must have either a @value, an @id, or extensions
*/

import React from 'react';
import { Link } from 'react-router';
import { TSlot } from '../../types/resources/Slot';

// Import all the partial resource
import Partials from '../../partials';
import { IdentifierSystem } from '../../utils/identifierSystem';

const Slot = ({ resource }: { resource: TSlot }): React.ReactElement => {
    const tagUUID = resource?.meta?.tag?.find((s) => s.system === IdentifierSystem.uuid)?.code;
    const uuid = tagUUID ? tagUUID : resource.id;

    return (
        <>
            <Link title="Direct link to Resource" to={`/4_0_0/${resource.resourceType}/${uuid}`}>
                {resource.resourceType}/{uuid}
            </Link>
            {
                resource.id !== undefined && resource.id !== null &&
                <Partials.String
                    string={resource.id}
                    name='Id'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='id'
                />
            }
            {
                resource.meta !== undefined && resource.meta !== null &&
                <Partials.Meta
                    meta={resource.meta}
                    name='Meta'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='meta'
                />
            }
            {
                resource.implicitRules !== undefined && resource.implicitRules !== null &&
                <Partials.Uri
                    uri={resource.implicitRules}
                    name='Implicit Rules'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='implicit-rules'
                />
            }
            {
                resource.language &&
                <Partials.Code code={resource.language} name='Language'/>
            }
            {
                resource.text !== undefined && resource.text !== null &&
                <Partials.Narrative
                    narrative={resource.text}
                    name='Text'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='text'
                />
            }
            {
                resource.extension !== undefined && resource.extension !== null &&
                <Partials.Extension
                    extension={resource.extension}
                    name='Extension'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='extension'
                />
            }
            {
                resource.modifierExtension !== undefined && resource.modifierExtension !== null &&
                <Partials.Extension
                    extension={resource.modifierExtension}
                    name='Modifier Extension'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='modifier-extension'
                />
            }
            {
                resource.identifier !== undefined && resource.identifier !== null &&
                <Partials.Identifier
                    identifier={resource.identifier}
                    name='Identifier'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='identifier'
                />
            }
            {
                resource.serviceCategory !== undefined && resource.serviceCategory !== null &&
                <Partials.CodeableConcept
                    codeableConcept={resource.serviceCategory}
                    name='Service Category'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='service-category'
                />
            }
            {
                resource.serviceType !== undefined && resource.serviceType !== null &&
                <Partials.CodeableConcept
                    codeableConcept={resource.serviceType}
                    name='Service Type'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='service-type'
                />
            }
            {
                resource.specialty !== undefined && resource.specialty !== null &&
                <Partials.CodeableConcept
                    codeableConcept={resource.specialty}
                    name='Specialty'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='specialty'
                />
            }
            {
                resource.appointmentType !== undefined && resource.appointmentType !== null &&
                <Partials.CodeableConcept
                    codeableConcept={resource.appointmentType}
                    name='Appointment Type'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='appointment-type'
                />
            }
            {
                resource.schedule !== undefined && resource.schedule !== null &&
                <Partials.Reference
                    reference={resource.schedule}
                    name='Schedule'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='schedule'
                />
            }
            {
                resource.status &&
                <Partials.Code code={resource.status} name='Status'/>
            }
            {
                resource.start !== undefined && resource.start !== null &&
                <Partials.Instant
                    instant={resource.start}
                    name='Start'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='start'
                />
            }
            {
                resource.end !== undefined && resource.end !== null &&
                <Partials.Instant
                    instant={resource.end}
                    name='End'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='end'
                />
            }
            {
                resource.overbooked !== undefined && resource.overbooked !== null &&
                <Partials.Boolean
                    boolean={resource.overbooked}
                    name='Overbooked'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='overbooked'
                />
            }
            {
                resource.comment !== undefined && resource.comment !== null &&
                <Partials.String
                    string={resource.comment}
                    name='Comment'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='comment'
                />
            }
        </>
    );
};

export default Slot;
