// This file is auto-generated by generate_components so do not edit manually

/**
SpecimenDefinition
    A kind of specimen with associated set of requirements.
    If the element is present, it must have either a @value, an @id, or extensions
*/

import React from 'react';
import { Link } from 'react-router';
import { TSpecimenDefinition } from '../../types/resources/SpecimenDefinition';

// Import all the partial resource
import Partials from '../../partials';
import { IdentifierSystem } from '../../utils/identifierSystem';

const SpecimenDefinition = ({ resource }: { resource: TSpecimenDefinition }): React.ReactElement => {
    const tagUUID = resource?.meta?.tag?.find((s) => s.system === IdentifierSystem.uuid)?.code;
    const uuid = tagUUID ? tagUUID : resource.id;

    return (
        <>
            <Link title="Direct link to Resource" to={`/4_0_0/${resource.resourceType}/${uuid}`}>
                {resource.resourceType}/{uuid}
            </Link>
            {
                resource.id !== undefined && resource.id !== null &&
                <Partials.String
                    string={resource.id}
                    name='Id'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='id'
                />
            }
            {
                resource.meta !== undefined && resource.meta !== null &&
                <Partials.Meta
                    meta={resource.meta}
                    name='Meta'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='meta'
                />
            }
            {
                resource.implicitRules !== undefined && resource.implicitRules !== null &&
                <Partials.Uri
                    uri={resource.implicitRules}
                    name='Implicit Rules'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='implicit-rules'
                />
            }
            {
                resource.language &&
                <Partials.Code code={resource.language} name='Language'/>
            }
            {
                resource.text !== undefined && resource.text !== null &&
                <Partials.Narrative
                    narrative={resource.text}
                    name='Text'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='text'
                />
            }
            {
                resource.extension !== undefined && resource.extension !== null &&
                <Partials.Extension
                    extension={resource.extension}
                    name='Extension'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='extension'
                />
            }
            {
                resource.modifierExtension !== undefined && resource.modifierExtension !== null &&
                <Partials.Extension
                    extension={resource.modifierExtension}
                    name='Modifier Extension'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='modifier-extension'
                />
            }
            {
                resource.identifier !== undefined && resource.identifier !== null &&
                <Partials.Identifier
                    identifier={resource.identifier}
                    name='Identifier'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='identifier'
                />
            }
            {
                resource.typeCollected !== undefined && resource.typeCollected !== null &&
                <Partials.CodeableConcept
                    codeableConcept={resource.typeCollected}
                    name='Type Collected'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='type-collected'
                />
            }
            {
                resource.patientPreparation !== undefined && resource.patientPreparation !== null &&
                <Partials.CodeableConcept
                    codeableConcept={resource.patientPreparation}
                    name='Patient Preparation'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='patient-preparation'
                />
            }
            {
                resource.timeAspect !== undefined && resource.timeAspect !== null &&
                <Partials.String
                    string={resource.timeAspect}
                    name='Time Aspect'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='time-aspect'
                />
            }
            {
                resource.collection !== undefined && resource.collection !== null &&
                <Partials.CodeableConcept
                    codeableConcept={resource.collection}
                    name='Collection'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='collection'
                />
            }
            {
                resource.typeTested !== undefined && resource.typeTested !== null &&
                <Partials.SpecimenDefinitionTypeTested
                    typeTested={resource.typeTested}
                    name='Type Tested'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='type-tested'
                    field=''
                />
            }
        </>
    );
};

export default SpecimenDefinition;
