// This file is auto-generated by generate_components so do not edit manually

/**
SubscriptionStatus
    The SubscriptionStatus resource describes the state of a Subscription during
    notifications.
    If the element is present, it must have either a @value, an @id, or extensions
*/

import React from 'react';
import { Link } from 'react-router';
import { TSubscriptionStatus } from '../../types/resources/SubscriptionStatus';

// Import all the partial resource
import Partials from '../../partials';
import { IdentifierSystem } from '../../utils/identifierSystem';
import PatientReferenceFromExtension from '../../partials/PatientReferenceFromExtension';

const SubscriptionStatus = ({ resource }: { resource: TSubscriptionStatus }): React.ReactElement => {
    const tagUUID = resource?.meta?.tag?.find((s) => s.system === IdentifierSystem.uuid)?.code;
    const uuid = tagUUID ? tagUUID : resource.id;

    return (
        <>
            <Link title="Direct link to Resource" to={`/4_0_0/${resource.resourceType}/${uuid}`}>
                {resource.resourceType}/{uuid}
            </Link>
            <PatientReferenceFromExtension extension={resource.extension} />
            {
                resource.id !== undefined && resource.id !== null &&
                <Partials.String
                    string={resource.id}
                    name='Id'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='id'
                />
            }
            {
                resource.meta !== undefined && resource.meta !== null &&
                <Partials.Meta
                    meta={resource.meta}
                    name='Meta'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='meta'
                />
            }
            {
                resource.implicitRules !== undefined && resource.implicitRules !== null &&
                <Partials.Uri
                    uri={resource.implicitRules}
                    name='Implicit Rules'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='implicit-rules'
                />
            }
            {
                resource.language &&
                <Partials.Code code={resource.language} name='Language'/>
            }
            {
                resource.text !== undefined && resource.text !== null &&
                <Partials.Narrative
                    narrative={resource.text}
                    name='Text'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='text'
                />
            }
            {
                resource.extension !== undefined && resource.extension !== null &&
                <Partials.Extension
                    extension={resource.extension}
                    name='Extension'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='extension'
                />
            }
            {
                resource.modifierExtension !== undefined && resource.modifierExtension !== null &&
                <Partials.Extension
                    extension={resource.modifierExtension}
                    name='Modifier Extension'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='modifier-extension'
                />
            }
            {
                resource.status &&
                <Partials.Code code={resource.status} name='Status'/>
            }
            {
                resource.type &&
                <Partials.Code code={resource.type} name='Type'/>
            }
            {
                resource.eventsSinceSubscriptionStart !== undefined && resource.eventsSinceSubscriptionStart !== null &&
                <Partials.String
                    string={resource.eventsSinceSubscriptionStart}
                    name='Events Since Subscription Start'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='events-since-subscription-start'
                />
            }
            {
                resource.notificationEvent !== undefined && resource.notificationEvent !== null &&
                <Partials.SubscriptionStatusNotificationEvent
                    notificationEvent={resource.notificationEvent}
                    name='Notification Event'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='notification-event'
                    field=''
                />
            }
            {
                resource.subscription !== undefined && resource.subscription !== null &&
                <Partials.Reference
                    reference={resource.subscription}
                    name='Subscription'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='subscription'
                />
            }
            {
                resource.topic !== undefined && resource.topic !== null &&
                <Partials.Canonical
                    canonical={resource.topic}
                    name='Topic'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='topic'
                />
            }
            {
                resource.error !== undefined && resource.error !== null &&
                <Partials.CodeableConcept
                    codeableConcept={resource.error}
                    name='Error'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='error'
                />
            }
        </>
    );
};

export default SubscriptionStatus;
