// This file is auto-generated by generate_components so do not edit manually

/**
SubscriptionTopic
    Describes a stream of resource state changes or events and annotated with
    labels useful to filter projections from this topic.
    If the element is present, it must have either a @value, an @id, or extensions
*/

import React from 'react';
import { Link } from 'react-router';
import { TSubscriptionTopic } from '../../types/resources/SubscriptionTopic';

// Import all the partial resource
import Partials from '../../partials';
import { IdentifierSystem } from '../../utils/identifierSystem';

const SubscriptionTopic = ({ resource }: { resource: TSubscriptionTopic }): React.ReactElement => {
    const tagUUID = resource?.meta?.tag?.find((s) => s.system === IdentifierSystem.uuid)?.code;
    const uuid = tagUUID ? tagUUID : resource.id;

    return (
        <>
            <Link title="Direct link to Resource" to={`/4_0_0/${resource.resourceType}/${uuid}`}>
                {resource.resourceType}/{uuid}
            </Link>
            {
                resource.id &&
                <Partials.String
                    string={resource.id}
                    name='Id'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='id'
                />
            }
            {
                resource.meta &&
                <Partials.Meta
                    meta={resource.meta}
                    name='Meta'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='meta'
                />
            }
            {
                resource.implicitRules &&
                <Partials.Uri
                    uri={resource.implicitRules}
                    name='Implicit Rules'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='implicit-rules'
                />
            }
            {
                resource.language &&
                <Partials.Code code={resource.language} name='Language'/>
            }
            {
                resource.text &&
                <Partials.Narrative
                    narrative={resource.text}
                    name='Text'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='text'
                />
            }
            {
                resource.extension &&
                <Partials.Extension
                    extension={resource.extension}
                    name='Extension'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='extension'
                />
            }
            {
                resource.modifierExtension &&
                <Partials.Extension
                    extension={resource.modifierExtension}
                    name='Modifier Extension'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='modifier-extension'
                />
            }
            {
                resource.url &&
                <Partials.Uri
                    uri={resource.url}
                    name='Url'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='url'
                />
            }
            {
                resource.identifier &&
                <Partials.Identifier
                    identifier={resource.identifier}
                    name='Identifier'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='identifier'
                />
            }
            {
                resource.version &&
                <Partials.String
                    string={resource.version}
                    name='Version'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='version'
                />
            }
            {
                resource.title &&
                <Partials.String
                    string={resource.title}
                    name='Title'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='title'
                />
            }
            {
                resource.derivedFrom &&
                <Partials.Canonical
                    canonical={resource.derivedFrom}
                    name='Derived From'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='derived-from'
                />
            }
            {
                resource.status &&
                <Partials.Code code={resource.status} name='Status'/>
            }
            {
                resource.experimental &&
                <Partials.Boolean
                    boolean={resource.experimental}
                    name='Experimental'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='experimental'
                />
            }
            {
                resource.date &&
                <Partials.DateTime
                    dateTime={resource.date}
                    name='Date'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='date'
                />
            }
            {
                resource.publisher &&
                <Partials.String
                    string={resource.publisher}
                    name='Publisher'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='publisher'
                />
            }
            {
                resource.description &&
                <Partials.Markdown
                    markdown={resource.description}
                    name='Description'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='description'
                />
            }
            {
                resource.jurisdiction &&
                <Partials.CodeableConcept
                    codeableConcept={resource.jurisdiction}
                    name='Jurisdiction'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='jurisdiction'
                />
            }
            {
                resource.purpose &&
                <Partials.Markdown
                    markdown={resource.purpose}
                    name='Purpose'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='purpose'
                />
            }
            {
                resource.copyright &&
                <Partials.Markdown
                    markdown={resource.copyright}
                    name='Copyright'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='copyright'
                />
            }
            {
                resource.approvalDate &&
                <Partials.Date
                    date={resource.approvalDate}
                    name='Approval Date'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='approval-date'
                />
            }
            {
                resource.lastReviewDate &&
                <Partials.Date
                    date={resource.lastReviewDate}
                    name='Last Review Date'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='last-review-date'
                />
            }
            {
                resource.effectivePeriod &&
                <Partials.Period
                    period={resource.effectivePeriod}
                    name='Effective Period'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='effective-period'
                />
            }
            {
                resource.resourceTrigger &&
                <Partials.SubscriptionTopicResourceTrigger
                    resourceTrigger={resource.resourceTrigger}
                    name='Resource Trigger'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='resource-trigger'
                    field=''
                />
            }
            {
                resource.eventTrigger &&
                <Partials.SubscriptionTopicEventTrigger
                    eventTrigger={resource.eventTrigger}
                    name='Event Trigger'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='event-trigger'
                    field=''
                />
            }
            {
                resource.canFilterBy &&
                <Partials.SubscriptionTopicCanFilterBy
                    canFilterBy={resource.canFilterBy}
                    name='Can Filter By'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='can-filter-by'
                    field=''
                />
            }
            {
                resource.notificationShape &&
                <Partials.SubscriptionTopicNotificationShape
                    notificationShape={resource.notificationShape}
                    name='Notification Shape'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='notification-shape'
                    field=''
                />
            }
        </>
    );
};

export default SubscriptionTopic;
