// This file is auto-generated by generate_components so do not edit manually

/**
SupplyRequest
    A record of a request for a medication, substance or device used in the
    healthcare setting.
    If the element is present, it must have either a @value, an @id, or extensions
*/

import React from 'react';
import { Link } from 'react-router';
import { TSupplyRequest } from '../../types/resources/SupplyRequest';

// Import all the partial resource
import Partials from '../../partials';
import { IdentifierSystem } from '../../utils/identifierSystem';

const SupplyRequest = ({ resource }: { resource: TSupplyRequest }): React.ReactElement => {
    const tagUUID = resource?.meta?.tag?.find((s) => s.system === IdentifierSystem.uuid)?.code;
    const uuid = tagUUID ? tagUUID : resource.id;

    return (
        <>
            <Link title="Direct link to Resource" to={`/4_0_0/${resource.resourceType}/${uuid}`}>
                {resource.resourceType}/{uuid}
            </Link>
            {
                resource.id !== undefined && resource.id !== null &&
                <Partials.String
                    string={resource.id}
                    name='Id'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='id'
                />
            }
            {
                resource.meta !== undefined && resource.meta !== null &&
                <Partials.Meta
                    meta={resource.meta}
                    name='Meta'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='meta'
                />
            }
            {
                resource.implicitRules !== undefined && resource.implicitRules !== null &&
                <Partials.Uri
                    uri={resource.implicitRules}
                    name='Implicit Rules'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='implicit-rules'
                />
            }
            {
                resource.language &&
                <Partials.Code code={resource.language} name='Language'/>
            }
            {
                resource.text !== undefined && resource.text !== null &&
                <Partials.Narrative
                    narrative={resource.text}
                    name='Text'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='text'
                />
            }
            {
                resource.extension !== undefined && resource.extension !== null &&
                <Partials.Extension
                    extension={resource.extension}
                    name='Extension'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='extension'
                />
            }
            {
                resource.modifierExtension !== undefined && resource.modifierExtension !== null &&
                <Partials.Extension
                    extension={resource.modifierExtension}
                    name='Modifier Extension'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='modifier-extension'
                />
            }
            {
                resource.identifier !== undefined && resource.identifier !== null &&
                <Partials.Identifier
                    identifier={resource.identifier}
                    name='Identifier'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='identifier'
                />
            }
            {
                resource.status &&
                <Partials.Code code={resource.status} name='Status'/>
            }
            {
                resource.category !== undefined && resource.category !== null &&
                <Partials.CodeableConcept
                    codeableConcept={resource.category}
                    name='Category'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='category'
                />
            }
            {
                resource.priority &&
                <Partials.Code code={resource.priority} name='Priority'/>
            }
            {
                resource.itemCodeableConcept !== undefined && resource.itemCodeableConcept !== null &&
                <Partials.CodeableConcept
                    codeableConcept={resource.itemCodeableConcept}
                    name='Item Codeable Concept'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='item-codeable-concept'
                />
            }
            {
                resource.itemReference !== undefined && resource.itemReference !== null &&
                <Partials.Reference
                    reference={resource.itemReference}
                    name='Item Reference'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='item-reference'
                />
            }
            {
                resource.quantity !== undefined && resource.quantity !== null &&
                <Partials.Quantity
                    quantity={resource.quantity}
                    name='Quantity'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='quantity'
                />
            }
            {
                resource.parameter !== undefined && resource.parameter !== null &&
                <Partials.SupplyRequestParameter
                    parameter={resource.parameter}
                    name='Parameter'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='parameter'
                    field=''
                />
            }
            {
                resource.occurrenceDateTime !== undefined && resource.occurrenceDateTime !== null &&
                <Partials.DateTime
                    dateTime={resource.occurrenceDateTime}
                    name='Occurrence Date Time'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='occurrence-date-time'
                />
            }
            {
                resource.occurrencePeriod !== undefined && resource.occurrencePeriod !== null &&
                <Partials.Period
                    period={resource.occurrencePeriod}
                    name='Occurrence Period'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='occurrence-period'
                />
            }
            {
                resource.occurrenceTiming !== undefined && resource.occurrenceTiming !== null &&
                <Partials.Timing
                    timing={resource.occurrenceTiming}
                    name='Occurrence Timing'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='occurrence-timing'
                />
            }
            {
                resource.authoredOn !== undefined && resource.authoredOn !== null &&
                <Partials.DateTime
                    dateTime={resource.authoredOn}
                    name='Authored On'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='authored-on'
                />
            }
            {
                resource.requester !== undefined && resource.requester !== null &&
                <Partials.Reference
                    reference={resource.requester}
                    name='Requester'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='requester'
                />
            }
            {
                resource.supplier !== undefined && resource.supplier !== null &&
                <Partials.Reference
                    reference={resource.supplier}
                    name='Supplier'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='supplier'
                />
            }
            {
                resource.reasonCode !== undefined && resource.reasonCode !== null &&
                <Partials.CodeableConcept
                    codeableConcept={resource.reasonCode}
                    name='Reason Code'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='reason-code'
                />
            }
            {
                resource.reasonReference !== undefined && resource.reasonReference !== null &&
                <Partials.Reference
                    reference={resource.reasonReference}
                    name='Reason Reference'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='reason-reference'
                />
            }
            {
                resource.deliverFrom !== undefined && resource.deliverFrom !== null &&
                <Partials.Reference
                    reference={resource.deliverFrom}
                    name='Deliver From'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='deliver-from'
                />
            }
            {
                resource.deliverTo !== undefined && resource.deliverTo !== null &&
                <Partials.Reference
                    reference={resource.deliverTo}
                    name='Deliver To'
                    resourceType={resource.resourceType}
                    id={uuid}
                    searchParameter='deliver-to'
                />
            }
        </>
    );
};

export default SupplyRequest;
