name: Create Artifact
run-name: ${{ github.workflow }}
on:
  release:
    types: [created]

jobs:
  Trigger-Build:
    runs-on: ubuntu-latest
    steps:
      - name: Upload Artifact
        id: upload_artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.ref_name }}
          path: ${{ github.workspace }}

      - name: Trigger Build Workflow
        run: |
          curl -X POST https://api.github.com/repos/icanbwell/helm.helix-service/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.GITHUB_TOKEN }} \
          --data '{"event_type": "trigger-fhir-server-ui-build", "client_payload": { "release_tag": "'"${{ github.ref_name }}"'", "artifact_url": "'"${{ steps.upload_artifact.outputs.artifact_url }}"'" }}'
