name: Create Artifact
run-name: ${{ github.workflow }}
on:
  release:
    types: [created]

jobs:
  Trigger-Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Master
        uses: actions/checkout@v3

      - name: Upload Artifact
        id: upload_artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.ref_name }}
          path: ./

      - name: print
        run: echo "${{ steps.upload_artifact.outputs.artifact-url }}"

      - name: Download code of fhir-server-ui from artifact
        run: 'curl -o source-code.zip -L -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" ${{ steps.upload_artifact.outputs.artifact-url }}'

      - name: Unzip source-code
        run: unzip source-code.zip -d ./

      - name: print
        run: ls -l

      - name: Trigger Build Workflow
        run: |
          curl -X POST https://api.github.com/repos/icanbwell/helm.helix-service/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.GITHUB_TOKEN }} \
          --data '{"event_type": "trigger-fhir-server-ui-build", "client_payload": { "release_tag": "'"${{ github.ref_name }}"'", "artifact_url": "'"${{ steps.upload_artifact.outputs.artifact-url }}"'" }}'
