name: Create Artifact
run-name: ${{ github.workflow }}
on:
  release:
    types: [created]

jobs:
  Upload-Source:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Master
        uses: actions/checkout@v3

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.ref_name }}
          path: ./
