name: Create Artifact
run-name: ${{ github.workflow }}
on:
  workflow_dispatch:
    inputs:
      env:
        type: string
        description: Env at which build will be deployed. (dev, staging, prod, perf, client-sandbox, etc.)
        required: true

jobs:
  Upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Master
        uses: actions/checkout@v3

      - name: Install dependencies
        run: yarn cache clean && yarn config delete proxy && yarn config delete https-proxy && yarn config delete registry && yarn install --no-optional --production=true --network-timeout 1000000

      - name: Build app
        run: yarn env:${{ github.event.inputs.env }} && yarn build:prod

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.ref_name }}-${{ github.event.inputs.env }}-ue1
          path: build/
