name: Upload Build
run-name: ${{ github.workflow }}
on:
  release:
    types: [created]

jobs:
  Upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Master
        uses: actions/checkout@v3

      - name: Install dependencies
        run: yarn cache clean && yarn config delete proxy && yarn config delete https-proxy && yarn config delete registry && yarn install --no-optional --production=true --network-timeout 1000000

      - name: Build app
        run: yarn env:dev && yarn build

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.ref_name }}
          path: build/
